### ISSUE TITLE
PocketStation Support

### ISSUE THREAD

**Issue by gledson999** [grumpycoders/pcsx-redux#1002]
This emulator project is pretty awesome, do you have plans to add PocketStation type Memory Card support?
So instead of the game recognizing it as a Memory Card, it will be able to recognize it as a PocketStation

**Comment by nicolasnoble** [comment]
We actually do, and it's currently in progress by @johnbaumann and @wheremyfoodat :)

**Comment by johnbaumann** [comment]
Some basic PocketStation command support was added via #995 . This can be toggled per slot through the Manage Memory Cards screen accessed via the Configuration menu.
