### ISSUE TITLE
PocketStation Write Error

### ISSUE THREAD

**Issue by gledson999** [grumpycoders/pcsx-redux#1019]
### Describe the bug

I was recently proposing here [#1002](https://github.com/grumpycoders/pcsx-redux/issues/1002) The PocketStation Support and was amazing support, but there is a bug or error.

I tested it with Pocket Digimon World Games and when it goes to save the progress after putting the Date, Name and Gender, it gives an error when saving/Writting to the Memory card (pocketStation).

![image](https://user-images.githubusercontent.com/31073450/200134696-3a95f56b-0597-4df1-9124-daf21f3e6bac.png)

So, when I see in memory card manager, show this.
![image](https://user-images.githubusercontent.com/31073450/200134791-cffe449c-f0ca-4896-b68a-61ee72b78ebd.png)

Instead this.
![image](https://user-images.githubusercontent.com/31073450/200134856-81c0e8c2-dcec-4570-a360-bb257e5d3bb5.png)

### Expected behavior

Error when Write

### Steps to reproduce the bug

Saving the game

### Operating System

Win10

### PCSX-Redux version

pcsx-redux-nightly-11123.20221105.8-x64

### CPU model

Intel Core i5

### GPU model

GTX 1050Ti Cerberus Edition

### BIOS version

OpenBIOS

### CPU emulation mode

Interpreter

### Additional information

Just This

**Comment by nicolasnoble** [comment]
Could you try with a retail bios instead of openbios?

**Comment by gledson999** [comment]
I tested it with SCPH1001.bin and PSXONPSP.bin (POPS PSP bios) and it worked perfectly.
Sorry for my mistake, I was supposed to do this test before reporting.

**Comment by nicolasnoble** [comment]
It's all good, it indicates the problem is with openbios :)

**Comment by johnbaumann** [comment]
Issue resolved
