### ISSUE TITLE
OpenBIOS compatibility for PlayStation emulators

### ISSUE THREAD

**Issue by davidhedlund** [grumpycoders/pcsx-redux#1027]
Is there a page for https://github.com/grumpycoders/pcsx-redux/tree/main/src/mips/openbios that lists compatibility status for notable and maintained free PlayStation emulators including:
* Retroarch cores: Beetle PSX HW, Beetle PSX, PCSX ReARMed, SwanStation)
* DuckStation
* PCSX-Reloaded

**Comment by nicolasnoble** [comment]
I don't have any desire nor time to dedicate testing OpenBIOS with other emulators than PCSX-Redux itself. The code is tested on both Redux and the real hardware. If there is a compatibility issue with another emulator that doesn't show neither in Redux nor the real hardware, then it's a bug in said emulator, and should be filed accordingly. General bugs with OpenBIOS should still be filed here: I don't have the attention span nor energy to look at more than one location for issues.

That being said, talking with @stenzek regularly, I know OpenBIOS works as well on his emulator as the retail hardware.

**Comment by davidhedlund** [comment]
Interesing. @stenzek What do you think about the idea of recommending OpenBIOS in the text at https://github.com/stenzek/duckstation ?

**Comment by davidhedlund** [comment]
@nicolasnoble Good work on the project! OpenBIOS is the only free BIOS that I'm aware of for PlayStation. Cheers.

**Comment by davidhedlund** [comment]
https://github.com/libretro/swanstation/issues/45

**Comment by davidhedlund** [comment]
> I don't have any desire nor time to dedicate testing OpenBIOS with other emulators than PCSX-Redux itself. The code is tested on both Redux and the real hardware. If there is a compatibility issue with another emulator that doesn't show neither in Redux nor the real hardware, then it's a bug in said emulator, and should be filed accordingly. General bugs with OpenBIOS should still be filed here: I don't have the attention span nor energy to look at more than one location for issues.
> 
> That being said, talking with @stenzek regularly, I know OpenBIOS works as well on his emulator as the retail hardware.

I can confirm that OpenBIOS works for Duckstation. I think OpenBIOS should be the default BIOS in Duckstation.

**Comment by wheremyfoodat** [comment]
> @nicolasnoble Good work on the project! OpenBIOS is the only free BIOS that I'm aware of for PlayStation. Cheers.

There is also the no$psx BIOS if you're interested. However it's not open source, actively maintained, and is pretty clumsy to use.

**Comment by wheremyfoodat** [comment]
> > I don't have any desire nor time to dedicate testing OpenBIOS with other emulators than PCSX-Redux itself. The code is tested on both Redux and the real hardware. If there is a compatibility issue with another emulator that doesn't show neither in Redux nor the real hardware, then it's a bug in said emulator, and should be filed accordingly. General bugs with OpenBIOS should still be filed here: I don't have the attention span nor energy to look at more than one location for issues.
> > That being said, talking with @stenzek regularly, I know OpenBIOS works as well on his emulator as the retail hardware.
> 
> I can confirm that OpenBIOS works for Duckstation. I think OpenBIOS should be the default BIOS in Duckstation.

Keep in mind OpenBIOS is not 100% compatible with retail games yet. As such, this decision would be a double-edged blade, as users might be confused when their games don't work because of the BIOS (implicitly) used.

**Comment by davidhedlund** [comment]
> > I can confirm that OpenBIOS works for Duckstation. I think OpenBIOS should be the default BIOS in Duckstation.
> 
> Keep in mind OpenBIOS is not 100% compatible with retail games yet. As such, this decision would be a double-edged blade, as users might be confused when their games don't work because of the BIOS (implicitly) used.

Thanks for your feedback, I really appreciate it.

**Comment by wheremyfoodat** [comment]
> > > I can confirm that OpenBIOS works for Duckstation. I think OpenBIOS should be the default BIOS in Duckstation.
> > 
> > 
> > Keep in mind OpenBIOS is not 100% compatible with retail games yet. As such, this decision would be a double-edged blade, as users might be confused when their games don't work because of the BIOS (implicitly) used.
> 
> Thanks for your feedback, I really appreciate it.

No problem.

**Comment by stenzek** [comment]
I'm going to add detection for OpenBIOS so that it doesn't show up as an unknown entry. But, I have no plans to ship any BIOS ROMs alongside the application itself. I was considering adding it an option in the "missing BIOS" dialog, however - with the risks that @wheremyfoodat pointed out.

As for the libretro core being broken, that has nothing to do with me, and is possibly violating copyright since they committed code which was never released as their own without attribution. So please don't tag me with any relation to it. I try to stay out of the public eye, because the trolling from those folks never ends.

**Comment by davidhedlund** [comment]
OpenBIOS also works fine with swanstation_libretro.so for Windows 11. I just tried it. @nicolasnoble

**Comment by nicolasnoble** [comment]
Hah, I didn't realize you were offering to do this sort of testing yourself :-) Good data, thanks!

As another data point, I know that OpenBIOS works properly on some other emulators, like [Avocado](https://github.com/JaCzekanski/Avocado) or the [PSX_MiSTer](https://github.com/MiSTer-devel/PSX_MiSTer).

I'm totally open in solving [problems people may encounter with using OpenBIOS](https://github.com/grumpycoders/pcsx-redux/issues/991), mind you, so feel free to file bugs. I'm also available on the [EmuDev subreddit and Discord server](https://www.reddit.com/r/EmuDev/) to discuss.

**Comment by davidhedlund** [comment]
> Hah, I didn't realize you were offering to do this sort of testing yourself :-) Good data, thanks!
> 
> As another data point, I know that OpenBIOS works properly on some other emulators, like [Avocado](https://github.com/JaCzekanski/Avocado) or the [PSX_MiSTer](https://github.com/MiSTer-devel/PSX_MiSTer).
> 
> I'm totally open in solving [problems people may encounter with using OpenBIOS](https://github.com/grumpycoders/pcsx-redux/issues/991), mind you, so feel free to file bugs. I'm also available on the [EmuDev subreddit and Discord server](https://www.reddit.com/r/EmuDev/) to discuss.

I spend last day to evaluate OpenBIOS (see the updated list in the top post) because I think it's the most important component in the emulator world right now. Only if developers are starting to ship emulators that require a BIOS with a free BIOSes they may be able to run games out of the box.

**Comment by davidhedlund** [comment]
To put things into perspective, please have a look for PCSX-redux at https://directory.fsf.org/wiki/Collection:Video_game_console_emulators#Sony -- I'm a long-term contributor and admin for the Free Software Directory and I'm cooperating closely with the Free Software Foundation.

It would be useful for us if you would like to re-open this issue so I can help you (I also have help with license experts) to promote and distribute free emulator BIOSes.

**Comment by davidhedlund** [comment]
https://github.com/grumpycoders/pcsx-redux/issues/1029

**Comment by davidhedlund** [comment]
@nicolasnoble I updated the top post table a lot. I think it would be useful to publish it in your repository after all. Would you please give it a chance?

**Comment by nicolasnoble** [comment]
So, several thoughts here.

 - Using the 240p test disc isn't really a good one because it's not an official software that wasn't written very well. The ISO has been badly mastered, and as you've seen, some emulators won't run it properly.
 - The list is probably something we'd want to have as a COMPATIBILITY.md file in the src/mips/openbios directory. Feel free to issue a PR if you want this properly stored in the repository in a more visible way.

As for help offered, thank you, but at the end of the day, I don't necessarily see much to be done from our end anyway? The code is here, fairly simple to build, using off the shelve Linux packages, and has already lots of flexible options allowing customizations. There's [Avocado](https://github.com/JaCzekanski/Avocado) for instance as an emulator that's shipping a customized version of OpenBIOS to display its logo instead of the boot cube, which is totally fair game. Unless there are hurdles to clear from our end, which I haven't seen identified at this time, the shipping and fixing would need to happen on these other emulator's release and distribution process.

**Comment by davidhedlund** [comment]
> So, several thoughts here.
> 
>     * Using the 240p test disc isn't really a good one because it's not an official software that wasn't written very well. The ISO has been badly mastered, and as you've seen, some emulators won't run it properly.

Good points. And 240pTestSuitePS1-EMU has not been maintained for 2 years. Do you know if there's any good and maintained test suite that is distributed as free software?

> 
>     * The list is probably something we'd want to have as a COMPATIBILITY.md file in the src/mips/openbios directory. Feel free to issue a PR if you want this properly stored in the repository in a more visible way.

I'm happy for your support! I suggested the COMPATIBILITY.md file here: https://github.com/grumpycoders/pcsx-redux/commit/c441041596c17ade06f7798faace142a570c650b

**Comment by lorn10** [comment]
@davidhedlund The following maybe already known but **PCSX-Reloaded** doesn't seems to work with the PSX OpenBIOS. Yes that emulator is super old but he is still present in the [repository](https://launchpad.net/ubuntu/+source/pcsxr) of Ubuntu. PCSX-Reloaded is even available for the newest Ubuntu editions and therefore (for ordinary people) easier to handle than PSCX-Redux . :wink: 

I have tested the OpenBIOS compatibility with the stock version of PCSX-Reloaded, package 1.9.94-4, on Kubuntu 20.04 LTS and **Crash Bandicoot 1**. I add this here just for the sake of completeness and if someone else wants to know about.

And by the way this interesting topic here would be better off in the [Discussions](https://github.com/grumpycoders/pcsx-redux/discussions) section. :+1:

**Comment by wheremyfoodat** [comment]
> 

Please read the relevant literature on why issues should be used over discussions sometimes before using discussions. 
https://github.com/grumpycoders/pcsx-redux/discussions/1082#discussioncomment-4246361

**Comment by davidhedlund** [comment]
> @davidhedlund The following maybe already known but **PCSX-Reloaded** doesn't seems to work with the PSX OpenBIOS. Yes that emulator is super old but he is still present in the [repository](https://launchpad.net/ubuntu/+source/pcsxr) of Ubuntu. PCSX-Reloaded is even available for the newest Ubuntu editions and therefore (for ordinary people) easier to handle than PCSX-Redux . wink
> 
> I have tested the OpenBIOS compatibility with the stock version of PCSX-Reloaded, package 1.9.94-4, on Kubuntu 20.04 LTS and **Crash Bandicoot 1**. I add this here just for the sake of completeness and if someone else wants to know about that.
> 
> And by the way this interesting topic here would be better off in the [Discussions](https://github.com/grumpycoders/pcsx-redux/discussions) section. +1

Thanks for your effort. Yes, the _pcsxr_ package exists in Ubuntu 22.04 as well, but the problem is that I couldn't use it (even with an original BIOS. Please give me exact instructions, and I'll give it a try again!

**Comment by lorn10** [comment]
I have checked it now again and the package is there, if you are on Ubuntu (or a derivative of it) just use `sudo apt install pcsxr`. 

This will install PCSX-Reloaded package **1.9.94-5build1**.

**Comment by davidhedlund** [comment]
> I have checked it now again and the package is there, if you are on Ubuntu (or a derivative of it) just use:
> 
> `sudo apt install pcsxr`
> 
> This will install PCSX-Reloaded package **1.9.94-5build1**.

I know that, but the BIOS doesn't work in it for me.
