### ISSUE TITLE
Breakpoints don't work at all with recompiler but only with interpreter

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1028]
### Describe the bug

I want to hack Castlevania Symphony of the Night.
When beginning a new game Richter starts with 30 hearts.
I managed to find the address of this quantity and I added a write breakpoint on this address.

When I collect new hearts or spend them by pressing triangle the PCSX-Redux does not break at all.

I viewed it in the breakpoints window and the write breakpoint is not disabled.

Is there something that I must do to make it work?

### Expected behavior

PCSX-Redux must break when an address, where a write breakpoint was set, has been written.

In my example when Richter gets more hearts or spends hearts by pressing triangle the hearts address is written and the write breakpoint that I set should cause PCSX-Redux to break.

### Steps to reproduce the bug

1. Play Castlevania Symphony of the Night USA region with scph1001.bin as the bios
2. Begin a new game. The name of the new game doesn't matter.
3. Add a write breakpoint of width 4 at 80097BA8 (this is the hearts quantity address).
4. Collect a heart or press triangle to spend them.
5. PCSX-Redux should break but it doesn't.

### Operating System

Windows 10

### PCSX-Redux version

pcsx-redux-nightly-11147.20221106.5-x64

### CPU model

Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz   3.70 GHz

### GPU model

Nvidia GeForce GTX 950

### BIOS version

SCPH1001.bin

### CPU emulation mode

Recompiler

### Additional information

I have said everything above

**Comment by nicolasnoble** [comment]
The debugger won't work properly with the dynarec enabled. Please turn it off and enable the debugger in the options.

**Comment by buruto** [comment]
> The debugger won't work properly with the dynarec enabled. Please turn it off and enable the debugger in the options.

I configured PCSX-Redux to use interpreter but this slowed my system so much that I had to restart it.

**Comment by nicolasnoble** [comment]
Your machine is more than capable to run Redux in interpreter mode at more than full speed. Heck, my laptop can easily get above 60fps when debugging. Did you enable tracing by any chance? If yes, disable it.

**Comment by buruto** [comment]
> Your machine is more than capable to run Redux in interpreter mode at more than full speed. Heck, my laptop can easily get above 60fps when debugging. Did you enable tracing by any chance? If yes, disable it.

Do you think that tracing slows down my system so much? If yes then how to disable it?

**Comment by nicolasnoble** [comment]
CPU Tracing is extremely taxing, but it should've been disabled by default. Maybe you've enabled it by mistake while trying to troubleshoot your root cause. Check the logs window, in the `Special` menu. This checkbox should be disabled.

Worst case scenario, you can reset Redux to its default settings by running it using the `-safe` command line option.

![image](https://user-images.githubusercontent.com/7281574/201565790-e7f5ef22-1551-4491-aafd-a0c895dcae53.png)

**Comment by buruto** [comment]
> 

I don't see this logs window. I will try the -safe option that you suggest.

**Comment by nicolasnoble** [comment]
The Logs window is accessible from the main `Debug` menu:

![image](https://user-images.githubusercontent.com/7281574/201566163-af7a1fb2-06c4-4a4c-a3d1-b136d54e7855.png)

**Comment by buruto** [comment]
> 

The CPU trace was checked. I unchecked it. Hope that this will solve this problem. I don't know why it was checked. I never seen this logs window before opened this issue.

**Comment by nicolasnoble** [comment]
Good :) Please try and report here.

**Comment by buruto** [comment]
> Good :) Please try and report here.

I am going to play Castlevania Symphony of the Night again and I will let you know if all problems are solved.

**Comment by wheremyfoodat** [comment]
@buruto Due to icache emulation or the recompiler caching executed code, sometimes changing an instruction with the memory editors might not work and the old code might keep being executed. This could be mitigated by either adding an option to flush the emulated CPU cache when the memory editor writes somewhere, or by adding a dedicated "flush cache" button in the GUI.

If you want to be able to assemble instructions by typing some MIPS code alq no$, that is probably coming eventually.

**Comment by nicolasnoble** [comment]
Regarding the movies being in the wrong color, did you enable the OpenGL renderer by any chance?

**Comment by buruto** [comment]
> Regarding the movies being in the wrong color, did you enable the OpenGL renderer by any chance?

Yes I did.

**Comment by buruto** [comment]
> @buruto Due to icache emulation or the recompiler caching executed code, sometimes changing an instruction with the memory editors might not work and the old code might keep being executed. This could be mitigated by either adding an option to flush the emulated CPU cache when the memory editor writes somewhere, or by adding a dedicated "flush cache" button in the GUI.
> 
> If you want to be able to assemble instructions by typing some MIPS code alq no$, that is probably coming eventually.

Changing MIPS instruction with the Memory Editor always worked for me while using the interpreter.

**Comment by buruto** [comment]
I have solved it.
