### ISSUE TITLE
Pcsx doesnt recognize new translations

### ISSUE THREAD

**Issue by Felipefpl** [grumpycoders/pcsx-redux#1036]
### Describe the bug

I translated pcsx to brazilian portuguese and it doesnt recognize the pt_BR.po file in the languages folder.

### Expected behavior

Recognize any translation file in the languages' folder.

### Steps to reproduce the bug

See above

### Operating System

Win7 x64

### PCSX-Redux version

pcsx-redux-nightly-11167.20221114.1-x64

### CPU model

Intel

### GPU model

Intel HD 2000

### BIOS version

Openbios

### CPU emulation mode

Recompiler

### Additional information

Btw, it doesnt make ANY sense to have the english .po file in the translated languages' section on transifex, it should be only in the english section.

**Comment by wheremyfoodat** [comment]
You need to update the src/core/system.cc to register the new translation.

**Comment by nicolasnoble** [comment]
How do you say Brazilian (the language) in Brazilian?

**Comment by StanleyKid-22** [comment]
Greetings.
3 months ago I applied for Ukrainian translation in the Transifex project. When trying to access the page, a 403 error occurs. Why is that?..

**Comment by nicolasnoble** [comment]
> Greetings. 3 months ago I applied for Ukrainian translation in the Transifex project. When trying to access the page, a 403 error occurs. Why is that?..

Ah, apologies, I missed the join notification. You should be good to go now.

**Comment by StanleyKid-22** [comment]
> > Greetings. 3 months ago I applied for Ukrainian translation in the Transifex project. When trying to access the page, a 403 error occurs. Why is that?..
> 
> Ah, apologies, I missed the join notification. You should be good to go now.

Great thanks!
I'll send translation later today.
