### ISSUE TITLE
Legend of Dragoon (USA) doesnt work

### ISSUE THREAD

**Issue by Felipefpl** [grumpycoders/pcsx-redux#1046]
### Describe the bug

After i load dragoon pcsx shows a black screen, nothing can be seen or heard.

### Expected behavior

game should work.

### Steps to reproduce the bug

Just load the game

### Operating System

Win7 x64

### PCSX-Redux version

Version: 11275.20221118.20.x64
Changeset: e8ba28b1735c932e4718592f0cea262874cd38f3
Date & time: 2022-11-18 14:30:45

### CPU model

Intel

### GPU model

Intel HD 2000

### BIOS version

OpenBios

### CPU emulation mode

Recompiler

### Additional information

My GPU has 100% support for OpenGL 3.1 and the game runs (with a BAD problem related to a graphic effect on transition to battle screen, it's slow on both emulators) on epsxe (with several plugins) and duckstation.

**Comment by johnbaumann** [comment]
Hi @Felipefpl , I'm unable to reproduce this problem on my side with the settings provided(nor with several other combinations I tried). Just wanted to confirm, you say the game will not boot at all, or will it not let you progress past a certain point?

Are you generally able to run other games with PCSX-Redux?

**Comment by nicolasnoble** [comment]
> Hi, i tried this suggestion with another game, wild arms, i tried to run with/without dynarec and even with scph7502 and it didnt work. Too bad the problem is on my side :/ - at least pcsx is fine. :P

Are you saying PCSX-Redux doesn't work at all for you? That's not good. Check the logs window?

**Comment by Felipefpl** [comment]
I checked the logs as you suggested and the blame is on me... :/

Glfw Error 65543: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
GLFW failed to create window with OpenGL core profile 3.2, retrying with any 3.0 profile
Warning: OpenGL error reporting disabled. See About dialog for more information.
Loading memory card memcard1.mcd
Loading memory card memcard2.mcd
Inicialização do PCSX-Redux
Copyright (C) 2019-2023 Autores do PCSX-Redux
BIOS carregada: C:\Downloads\Emuladores\ePSXe205\bios\SCPH7502.bin
BIOS conhecida detectada: SCPH-7502 (EU) (649db764)
Imagem do CD Carregada: C:\Downloads\Emuladores\Legend of Dragoon, The (USA) (Disc 1).bin[+cue].
Faixa 01 (DATA) - Início 00:02:00, Duração 45:49:12
Rótulo do CD-ROM: SCUS94491
ID do CD-ROM: SCUS94491
Nome do EXE do CD-ROM: SCUS_944.91;1

Out of curiosity, why opengl 3 is needed to emulate pcsx? I mean, the videogame is from 1994. This got to do with simpler to code and stuff?

**Comment by nicolasnoble** [comment]
I just realized you put `Intel HD 2000` in the list. I actually have a machine with this GPU, and Redux works fine for me on it. What exactly do you have on screen?  Do you hear anything? What's the behavior exactly? The top menu shouldn't even appear to be honest if this was an OpenGL problem, so something else must be afoot.

**Comment by Felipefpl** [comment]
This is what i see AFTER i load legend of dragoon or wild arms, i cant hear any sound being done by the game.

![Black screen](https://user-images.githubusercontent.com/5569804/203445668-b3723ce0-6789-475c-8434-bf39f1397669.gif)

**Comment by nicolasnoble** [comment]
Did you... do Emulation->Start to power on the console?

**Comment by Felipefpl** [comment]
> Did you... do Emulation->Start to power on the console?

Nope, i didnt know that. I thought i just had to click 2x in the image file like we do with other emulators and pcsx would start the game right away. :/

Now i have another problem, legend of dragoon starts but gets stuck in the screen below:

![Stuck](https://user-images.githubusercontent.com/5569804/203545536-28009288-dbfc-40e5-b1f5-1a756220a123.gif)

Here is a log of what ocurred, i tried both scph7502 and openbios, both gave the same result:

Glfw Error 65543: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
GLFW failed to create window with OpenGL core profile 3.2, retrying with any 3.0 profile
Warning: OpenGL error reporting disabled. See About dialog for more information.
Loading memory card memcard1.mcd
Loading memory card memcard2.mcd
PCSX-Redux booting
Copyright (C) 2019-2022 PCSX-Redux authors
Loaded BIOS: C:\Downloads\Emuladores\pcsx-redux-nightly-11480.20221121.4-x86\openbios.bin
OpenBIOS detected (fbe75b59)
Loaded CD Image: C:\Downloads\Emuladores\Legend of Dragoon, The (USA) (Disc 1).bin[+cue].
Track 01 (DATA) - Start 00:02:00, Length 45:49:12
CD-ROM Label: SCUS94491
CD-ROM ID: SCUS94491
CD-ROM EXE Name: SCUS_944.91;1
================
uC-sdk - booting
================
BIOS Trace1: 0x0f
BIOS Trace1: 0x0e
BIOS Trace1: 0x01
BIOS Trace1: 0x02
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x01
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x05
BIOS Trace1: 0x06
BIOS Trace1: 0x02
BIOS Trace1: 0x05
PS-X Realtime Kernel OpenBios - build id 6529b3f3de15692586bf2ccf8d3dbe5cc7cabc3b.
Copyright (C) 2019-2022 PCSX-Redux authors.
BIOS Trace1: 0x06
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
BIOS Trace1: 0x07
*** OpenBIOS tiny shell - starting ***
*** Data is acceptable, booting now. ***
BIOS Trace1: 0x08
BOOTSTRAP LOADER
BIOS Trace1: 0x09
setup file    : cdrom:SYSTEM.CNF;1
TCB	00000004
EVENT	00000010
STACK	801ffff0
BOOT =	cdrom:\SCUS_944.91;1
argument =	
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
boot file     : cdrom:\SCUS_944.91;1
EXEC:PC0(801bf4e8)  T_ADDR(80188888)  T_SIZE(0003e000)
boot address  : 801bf4e8 801ffff0
Execute !
                S_ADDR(801ffff0)  S_SIZE(00000000)
Change effective memory : 2 MBytes
Found C0 patch hash 2a81bbef "_patch_card#2", issued from 0x8002d92c, executing...
Found B0 patch hash c29df18f "_patch_card2#2", issued from 0x8002d9c0, executing...
Found B0 patch hash 5123f82a "_patch_card_info#1", issued from 0x8002d848, executing...
Saving memory card memcard1.mcd
Saving memory card memcard2.mcd
Saving memory card memcard1.mcd
Saving memory card memcard2.mcd
ResetGraph:jtb=80054674,env=800546bc
Unknown command for pad: 43
ResetGraph:jtb=80054674,env=800546bc
Found C0 patch hash 61c914a1 "_patch_gte#1", issued from 0x80040d30, executing...
Found C0 patch hash 61c914a1 "_patch_gte#1", issued from 0x80040d30, executing...
CD_init:addr=80053224
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43

**Comment by Felipefpl** [comment]
@nicolasnoble - now i have another problem with pcsx-redux, i cant start the emulator on win7, was the support for this system removed? When i start the emulator i see a white screen for 2 seconds and then it closes. Downloaded the emu from github.

**Comment by nicolasnoble** [comment]
Windows 7 support was never really officially there in the first place. Nobody on the team has any Win7 machine to test, and Microsoft routinely releases updates to their compiler which may break backwards compatibility with their out-of-support operating systems. This is way out of our control.

**Comment by Felipefpl** [comment]
Ok then, thanks for the reply.
