### ISSUE TITLE
The tabbed window is flickering and can't be used when the tabs "Assembly" and "Symbols" are open

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1064]
Recently I noticed that in PCSX-Redux the user can take multiple different windows and turn them into multiple different tabs in one window.

I have taken both the "Assembly" and the "Symbols" windows and made a one window with two tabs: "Assembly" and "Symbols" but now the window that contains these two tabs always flickers and I can't use it at all.

I also can't undo this action and I must reboot PCSX-Redux.

I still can use both "Assembly" and "Symbols" as two separated windows instead of tabs in one window but I like to be a user of one window which has a lot of open tabs.

This is much more convenient for me to work this way.

Why I have this problem when both "Assembly" and "Symbols" are two different tabs of one window? Is this a bug that has to be fixed in a future build and release of PCSX-Redux?

**Comment by nicolasnoble** [comment]
I'd need to see what you're talking about exactly, possibly with a video taken with [OBS](https://obsproject.com/), but this feels like a bug either with ImGui or with GLFW or both, not with Redux itself directly.

Do you have multiple monitors? Windows, Linux, or MacOS? Do you have a high DPI display?

**Comment by buruto** [comment]
> I'd need to see what you're talking about exactly, possibly with a video taken with [OBS](https://obsproject.com/), but this feels like a bug either with ImGui or with GLFW or both, not with Redux itself directly.
> 
> Do you have multiple monitors? Windows, Linux, or MacOS? Do you have a high DPI display?

I am a Windows 64 bit user and I have a single monitor only.

**Comment by nicolasnoble** [comment]
What... would possibly cause this flicker... impressive, I've never seen this before. I'll try to reproduce it.

**Comment by buruto** [comment]
> What... would possibly cause this flicker... impressive, I've never seen this before. I'll try to reproduce it.

The steps to reproduce the issue are very simple:

1. In the Debug menu show the Assembly window.
2. In the Assembly window click on the Symbols button to show the Symbols window.
3. Either Drag the Symbols window into the Assembly window or Assembly window into the Symbols window

**Comment by buruto** [comment]
I have solved it.
