### ISSUE TITLE
(Windows) Minimizing main window, then closing it causes bad pcsx.json values

### ISSUE THREAD

**Issue by fuerchter** [grumpycoders/pcsx-redux#1066]
### Describe the bug

See the descriptions below.

### Expected behavior

Closing the program while minimized does not cause any issues on subsequent launches

### Steps to reproduce the bug

1. Start PCSX-Redux on a Windows machine (I could not reproduce this on Ubuntu 22.04.1 LTS)
2. Minimize the main window (titled "PCSX-Redux")
3. Right-click the program in the task bar and close it
(Notice how in pcsx.json "WindowPosX" is set to -32000 now, as is "WindowPosY")
5. Start PCSX-Redux again
6. The main window is shown in white when alt-tabbing and is inaccessible
![image](https://user-images.githubusercontent.com/3199489/203656696-ed41f68c-f442-44f1-915e-86ec57ddc9f5.png)
![image](https://user-images.githubusercontent.com/3199489/203656728-04acce36-fe6f-4a47-8754-2bdc047da627.png)
8. Notice how restarting PCSX-Redux after this still doesn't fix the issue. Resetting the mentioned pcsx.json values does e.g.

### Operating System

Windows 11 64-bit

### PCSX-Redux version

Version: 11559.20221123.4.x64
Changeset: 1c2be2ab90bf30189d4efbf42ede7900b30a7176
Date & time: 2022-11-23 07:15:40

### CPU model

AMD Ryzen 5 3600 6-Core Processor 3.59 GHz

### GPU model

NVIDIA Geforce GTX 1660 SUPER

### BIOS version

OpenBIOS detected (fbe75b59)

### CPU emulation mode

Interpreter

### GPU emulation mode

Software

**Comment by wheremyfoodat** [comment]
This issue has been around since like 2019 and seems to be kinda difficult to reproduce (eg I used to get it constantly and never get it now) which makes it worse. I will try to add a small workaround that might fix this.

**Comment by nicolasnoble** [comment]
Hopefully, #1069 will address this.

**Comment by fuerchter** [comment]
This looks fixed in the current Windows version (and as discussed on discord). Thanks!
