### ISSUE TITLE
Both the main window and the debug windows and tabs receive focus and respond to keyboard

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1068]
I am using the Debug menu and windows of PCSX-Redux a lot to hack PS1 roms, not just play them without Cheat Engine at all.

This is the reason that PCSX-Redux is my favourite PS1 emulator among all PS1 emulators and not ePSXe that doesn't provide any debugging and hacking tools at all.

But when I am not playing the game but busy with a debug window or tab like Memory Observer, Assembly, Memory Editor, Breakpoints, Registers and etc, the game still receives keyboard input and responds to key presses that I do to change some bytes and words with the Memory Editor or entering a number in the Memory Observer and this is pretty annoying.

I always have to **remember** to manually pause the emulation with the F6 key on my keyboard before switching to a debug window or tab and **NOT** hear the nice music, song or track that is played in the background with my headphones or headsets!

Please fix this annoying issue! I am suffering a lot from this issue!

**Comment by nicolasnoble** [comment]
Yes, we need a proper grand dispatcher of events, but this requires a fairly non-trivial refactor of the codebase.

Workarounds in the meantime include the following:
 - you can disconnect the pad from the pads configuration
 - you can plug in a physical pad, which will then take over from the keyboard completely

**Comment by buruto** [comment]
> Yes, we need a proper grand dispatcher of events, but this requires a fairly non-trivial refactor of the codebase.
> 
> Workarounds in the meantime include the following:
> 
> * you can disconnect the pad from the pads configuration
> * you can plug in a physical pad, which will then take over from the keyboard completely

Understood.

**Comment by buruto** [comment]
I have solved it.
