### ISSUE TITLE
All the commands of the context menu of the Assembly window or tab are repeated twice when the current instruction is right clicked

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1088]
In the Assembly window or tab the yellow arrow shows the current position of the PC register and the instruction that the PC is about to execute.

If you right click this instruction then a context menu appears and all the commands appear **twice**: Copy Address, Go to in Memory Editor, Run to Cursor and Toggle Breakpoint.

![image](https://user-images.githubusercontent.com/22644072/204475566-db335efd-0809-4b54-bce1-916cba4af4ee.png)

The red rectangle that I made with the Microsoft Paint software was to show all the duplicates that PCSX-Redux should **NOT** show to the user at all because there is no point in doing so, don't you agree with me?

Also clicking on any of the duplicates below doesn't seem to do anything either.

I discovered this issue **very long time ago** and wanted to report this issue **earlier** but I **forgot**! Only now I remember! I am also a human exactly like you and also imperfect being.

**Comment by wheremyfoodat** [comment]
Can't seem to reproduce
![image](https://user-images.githubusercontent.com/44909372/204892596-284b15d1-a50b-4226-a1be-a8e0389498d7.png)

**Comment by wheremyfoodat** [comment]
OK it seems like it only occurs with specific addresses
![image](https://user-images.githubusercontent.com/44909372/204893314-5815b699-f13e-47fa-b552-de25c217844e.png)

**Comment by buruto** [comment]
> OK it seems like it only occurs with specific addresses ![image](https://user-images.githubusercontent.com/44909372/204893314-5815b699-f13e-47fa-b552-de25c217844e.png)

So are you working on this?

**Comment by buruto** [comment]
I have solved it.
