### ISSUE TITLE
The "Configure Shaders" command in the "Configuration" menu does nothing on mouse left button click

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1109]
I want to configure the shaders of a PS1 rom that I am playing but clicking on the "Configure Shaders" in the "Configuration" menu just does nothing.

What do you think the problem is?

**Comment by wheremyfoodat** [comment]
You seem to be misusing the "configure shaders" button. If you want to edit the different types of shaders you should use

- Debug -> Show output shader editor (To edit the shader used before outputting the image on screen)
- Debug -> Show offscreen shader editor (To edit the postprocessing shader)
- [If using the OpenGL GPU] Configuration -> GPU -> Show shader editor to edit the shaders that determine how the OpenGL GPU core renders PS1 triangles.

Shaders like the built-in CRT shader have lua scripts attached to them that spawn Imgui menus which let you configure various settings. The "configure shaders" button is used to display these menus. Here's what you get if you click on the button while using the CRT shader
![image](https://user-images.githubusercontent.com/44909372/204883250-6ac0158c-10d8-4a7d-9928-7542686e7685.png)

**Comment by buruto** [comment]
> You seem to be misusing the "configure shaders" button. If you want to edit the different types of shaders you should use
> 
> * Debug -> Show output shader editor (To edit the shader used before outputting the image on screen)
> * Debug -> Show offscreen shader editor (To edit the postprocessing shader)
> * [If using the OpenGL GPU] Configuration -> GPU -> Show shader editor to edit the shaders that determine how the OpenGL GPU core renders PS1 triangles.
> 
> Shaders like the built-in CRT shader have lua scripts attached to them that spawn Imgui menus which let you configure various settings. The "configure shaders" button is used to display these menus. Here's what you get if you click on the button while using the CRT shader ![image](https://user-images.githubusercontent.com/44909372/204883250-6ac0158c-10d8-4a7d-9928-7542686e7685.png)

PCSX-Redux should tell me what I am doing wrong instead of doing nothing.
