### ISSUE TITLE
pcsx-redux.main - System Error

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1135]
> The code execution cannot proceed because libgcc_s_dw2-1.dll was not found. Reinstalling the program may fix this problem.

Shows itself to me several times when I am trying to run pcsx-redux-nightly-12024.20221207.7-x86 and I don't know why.

I did download and install the x86 version of Microsoft Visual C++ Redistributable 2015-2022 as the first error message box asked me to do but still this error message box shows itself to me several times so even the x86 version of PCSX-Redux can't be used to play my PlayStation roms at all.

I guess that I will have to temporarily start using DuckStation without read and write breakpoints but to play my PlayStation roms. I still can use it's cheats list and memory scanner with the freeze feature of cheat manager though.

DuckStation is still working for me and plays my PlayStation roms with excellent compatibility, speed and performance.

But since I still prefer to use both read and write breakpoints and memory editor to make my own cheats, which unfortunately DuckStation currently still lacks, I will go back to PCSX-Redux once these errors are corrected and solved.

Or I can try the Linux Intel 64-bit (AppImage) with windows subsystem for Linux.

**Comment by nicolasnoble** [comment]
Try the 64bits build?

**Comment by buruto** [comment]
> Try the 64bits build?

I already tried the 64bits build before the 32bits build and the 64bits (both non-cli and cli) didn't work for me.

There is a reason that I started both:

#1133 and #1134) before I started #1135

**Comment by nicolasnoble** [comment]
Fixed by #1136.
