### ISSUE TITLE
pcsx-redux-nightly-12039.20221207.11-x64 does no longer open, boot and play Castlevania Symphony of the Night whose game ID is SLUS00067 by the way for me

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1137]
No error message boxes. It just does nothing. It appears that all 12019, 12028 cli and 12048 cli also don't play this game if I tell Auto Update that I don't want to update.

This keep happening on both 12051 and 12060 cli if I disable Auto Update and don't update.

Both 11851.20221203.7.x64 and 11860.20221203.9.x64-cli were the last versions of PCSX-Redux that could actually open, boot and play this game whose ID is SLUS00067 by the way for me.

**Comment by buruto** [comment]
> So this has been successfully tested using this build with both retail bioses and openbios.
> 
> ![image](https://user-images.githubusercontent.com/7281574/206335113-e905860b-e7e1-4fe0-a62d-31c7cfc44d03.png) ![image](https://user-images.githubusercontent.com/7281574/206335132-3d2d32a9-77d7-4710-8805-3790ddf76169.png)
> 
> You may want to try the Debug->Show Logs window to see if there's anything displayed there that might indicate what's going on. Feel free to copy/paste the contents of the logs here so we can analyze too.

How did you run this? I tried "File => open disk" and selected the cue file.

**Comment by nicolasnoble** [comment]
You then need to start emulation using Emulation->Start.

The emulator functions like a real console. You've inserted a disk, then you need to press power.

**Comment by nicolasnoble** [comment]
So, what's in the logs?

**Comment by buruto** [comment]
> So, what's in the logs?

Where to find the logs file?

**Comment by nicolasnoble** [comment]
As I said, Debug -> Show Logs.

**Comment by nicolasnoble** [comment]
There's a `copy` button on top of the Logs window. You can then paste here.

**Comment by buruto** [comment]
> Thanks, I know what's wrong. I'll fix it tonight.

You read it very quickly.

**Comment by nicolasnoble** [comment]
I managed to get my hand on this iso image. It's hopelessly broken in many ways. The parser fix will somewhat make it work, but it's not ideal.

**Comment by buruto** [comment]
> I managed to get my hand on this iso image. It's hopelessly broken in many ways. The parser fix will somewhat make it work, but it's not ideal.

Interesting that both 11851.20221203.7.x64 and 11860.20221203.9.x64-cli are able to open, boot and play this image properly.

And the image is not an iso file but a bin file of about 500 MB and a cue file less than 1 KB that appears to be a text file at all.
