### ISSUE TITLE
PCSX-Redux is not backward compatible with memory cards at all

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1153]
I imported all the memory cards by copying both `memcard1.mcd` and `memcard2.mcd` from pcsx-redux-nightly-12092.20221209.8-x64-cli to pcsx-redux-nightly-12144.20221212.3-x64-cli but 12144 can neither display nor load the saved game that was done by 12092 in the new game screen of Castlevania Symphony of the Night whose game ID is SLUS00067.

This is pretty strange because PCSX-Redux is backward compatible with savestates, I mean with 12144 I could load a state which was saved by 12092, so why not memory cards too???

**Comment by wheremyfoodat** [comment]
It's the opposite way. Memory card images are fully backwards compatible as they're just a raw dump of a memory card's contents. Savestates on the other hand aren't fully backwards compatible and can break, albeit we avoid that.

Make sure you've properly copied the memory card, that you turned Redux off and on (with the X button, not by pressing reboot), and that you're using the same iso as the one you used to make the save.

**Comment by buruto** [comment]
> It's the opposite way. Memory card images are fully backwards compatible as they're just a raw dump of a memory card's contents. Savestates on the other hand aren't fully backwards compatible and can break, albeit we avoid that.
> 
> Make sure you've properly copied the memory card, that you turned Redux off and on after pasting the card (with the X button, not by pressing reboot), and that you're using the same iso as the one you used to make the save.

I don't have an iso file of the game. The game is a pair of a bin file about 500 MB in size and a cue text file less than 1 KB in size and I have only one image of the game.

But I really didn't think to quit PCSX-Redux and rerun it. I also didn't think to reboot PCSX-Redux either.

This is strange why you are saying that the reboot approach doesn't work in general.

Anyway I have got pcsx-redux-nightly-12176.20221213.4-x64-cli and without enabling Auto Update I have successfully loaded the memory cards of pcsx-redux-nightly-12092.20221209.8-x64-cli.
