### ISSUE TITLE
There is no "Float" value type in the "Delta-over-time search" tab of the "Memory Observer" window of the PCSX-Redux PlayStation emulator

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1202]
There is "Int" there but for integers only but not "Float" for fractional numbers too like in C, C++, C# and Java at all.

Why?

**Comment by nicolasnoble** [comment]
This would be completely meaningless, pointless, and senseless. The PSX CPU has no floats. Searching for floats in memory would be an exercise in futility since it can't produce them in the first place.

**Comment by buruto** [comment]
> This would be completely meaningless, pointless, and senseless. The PSX CPU has no floats. Searching for floats in memory would be an exercise in futility since it can't produce them in the first place.

If that so then how 3D games, like Crash Bandicoot, work on the PSX at all?

Are vectors (X, Y and Z coordinates) not floats?

**Comment by wheremyfoodat** [comment]
It's all fixed point arithmetic and you can look at the documentation or Redux code to verify it.

**Comment by buruto** [comment]
> It's all fixed point arithmetic and you can look at the documentation or Redux code to verify it.

And the CPU of the PSX supports fixed point arithmetic?

If that so then I would like to have "Fixed" value type there then.

**Comment by nicolasnoble** [comment]
Alright, I am going to say this, as gently as I can: you clearly have no understanding on how the PlayStation works, nor even how math works, and this is becoming embarrassing at this point.

**Comment by buruto** [comment]
> Alright, I am going to say this, as gently as I can: you clearly have no understanding on how the PlayStation works, nor even how math works, and this is becoming embarrassing at this point.

Maybe I am dumb.
