### ISSUE TITLE
The "Go to the nearest branch or jump instruction that skips this instruction" action is missing from the context menu of the Assembly window or tab

### ISSUE THREAD

**Issue by buruto** [grumpycoders/pcsx-redux#1204]
I am just migrating the https://github.com/grumpycoders/pcsx-redux/discussions/1203 feature request from the Discussions tab to the Issues tab according to wheremyfoodat's request:

> Could you try using the issues tab for feature requests rather than the discussion tab?

Now, unlike discussion, you can close this issue when this feature is implemented in PCSX-Redux.

**Comment by nicolasnoble** [comment]
Please stop opening *both* issues and discussions. Just create issues, not discussions, with the body of your idea here, as an issue.

And for what you're trying to do, this is exactly what the [execution mapping](https://pcsx-redux.consoledev.net/advanced_features/#mapping-breakpoints) is for. You start playing a game, you activate execution mapping, continuing to play while avoiding damage. Then you activate breakpoint on execution mapping, and go take damage on purpose. The emulation will most likely stop exactly where the branching occurred.
