### ISSUE TITLE
Memory Card Saving Issue - Digimon World 2

### ISSUE THREAD

**Issue by LatchGameDev** [grumpycoders/pcsx-redux#1255]
### Describe the bug

When attempting to make a save the game always doesn't see a save file / properly formatted memory card and will keep asking if I want to make a save file. Attempted to change from open bios to the normal bios and it still was happening. Not sure if I did the change correctly so it might work for you. So for now will just use save states.

Video Of Issue:
[https://www.youtube.com/watch?v=3tbCXjVKbJk](url)

This happened on a fresh install, never used this emulator before and this was the first game I started using it with. 

### Expected behavior

On real hardware after asking me to save the file it should format the memory card. The next screen should show me three possible save slots to save my game to. The bar in the lower right also should be slowly filling up as it formats the card and again when it saves the game.

 

### Steps to reproduce the bug

1. Start a new game or attempt to load a game
2. Get far enough where you can try to save (a world/city screen basically)
3. Attempt saving

### Operating System

Windows 10

### PCSX-Redux version

Version: 14051.20230323.2.x64
Changeset: 28393673555c1de6a32516fb7819c2e4f609018b
Date & time: 2023-03-22

### CPU model

AMD Ryzen 5 3600X 6-Core Processor  3.80 GHz

### GPU model & Drivers

Nvidia Geforce RTX 2060/PCIe/SSE2 - Version:3.2.0 Nvidia 516.94 - Shading language version: 1.50 Nvidia via Cg Compiler

### BIOS version

OpenBios

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [X] Debugger

**Comment by johnbaumann** [comment]
I've confirmed this behavior when using OpenBIOS. On my end it seems to work ok with the retail bios. Changing the bios file and then performing a hard reset through the menu should be enough to switch, however, loading a savestate will replace the bios with the one that was loaded when the savestate was created.

**Comment by newhinton** [comment]
I think i have the same issue, with a different game. When i try to save Discworld, i get a "Save Error" message. Is there any way around this?

**Comment by wheremyfoodat** [comment]
> I think i have the same issue, with a different game. When i try to save Discworld, i get a "Save Error" message. Is there any way around this?

Try using a retail BIOS in case you're using OpenBIOS. The latter is known to have some memory card issues here and there.

**Comment by newhinton** [comment]
Sadly i dont have access to one outside openbios and the ps3 one. The latter does not work with psx-rearmed (which i use on my pi). I know that there are other sources, but i would like to stay away from those.

**Comment by wheremyfoodat** [comment]
> Sadly i dont have access to one outside openbios and the ps3 one. The latter does not work with psx-rearmed (which i use on my pi). I know that there are other sources, but i would like to stay away from those.

In that case you'll have to wait until the memcard problems in openbios are figured out and fixed :/

**Comment by nicolasnoble** [comment]
Sorry I was out of commission for a few days. Very very useful bug report, thanks. I'll try and have a look, as it seems pretty reproducible.

**Comment by nicolasnoble** [comment]
Hmmm, it turns out that the requirements to reproduce are a bit harsh, since it requires playing the game quite a bit before hitting the problem...

**Comment by nicolasnoble** [comment]
Well, no, it wasn't that hard at the end of the day.

#1367 should hopefully fix this one.

**Comment by nicolasnoble** [comment]
Could you please retry with latest and confirm this now fully works for you ?

**Comment by johnbaumann** [comment]
Haven't heard back from OP in a while, and I believe this problem has been resolved. Marking this one as closed, feel free to reopen if you are still experiencing issues.
