### ISSUE TITLE
Yu-Gi-Oh! Forbidden Memories Graphical Issues

### ISSUE THREAD

**Issue by cultrupt** [grumpycoders/pcsx-redux#1313]
### Describe the bug

The game ran fine in version 14810.20230521.2.x64 . However, the latest update(s) broke the game graphics and it is now unplayable.

![SLUS-01411 B](https://github.com/grumpycoders/pcsx-redux/assets/119785807/027f7212-6be4-4eaf-84b5-ae62adac9f9a)
![SLUS-01411 A](https://github.com/grumpycoders/pcsx-redux/assets/119785807/9c72988b-c3b6-44e2-9724-b82e7993d015)

### Expected behavior

The game should run without graphical issues.

### Steps to reproduce the bug

1. Open the game
2. Press Starts
3. Press X to start a new game

### Operating System

Microsoft Windows 10 Pro

### PCSX-Redux version

Version: 14864.20230527.2.x64
Changeset: 261fbdf208fb0572377ee7a8572863ca37fec794
Date & time: 2023-05-27 06:16:48

### CPU model

Intel(R) Core(TM) i7-9750H

### GPU model & Drivers

NVIDIA GeForce GTX 1660 Ti Max-Q GPU Driver 535.98

### BIOS version

SCPH5501

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

### Logs

Warning: OpenGL error reporting disabled. See About dialog for more information.

Got an unknown GPU data word: 0007924c
Got an unknown GPU data word: 0007924c
BIOS Trace1: 0x00
BIOS Trace1: 0x01
System Controller ROM Version 98/06/10 c3
BIOS Trace1: 0x02
BIOS Trace1: 0x00
SetGraphDebug:level:1,type:0 reverse:0
BIOS Trace1: 0x05
BIOS Trace1: 0x08
BOOTSTRAP LOADER Type C Ver 2.1   03-JUL-1994
Copyright 1993,1994 (C) Sony Computer Entertainment Inc.
BIOS Trace1: 0x09
setup file    : cdrom:SYSTEM.CNF;1
TCB	00000004
EVENT	00000016
STACK	801fff00
BOOT =	cdrom:\SLUS_014.11;1
argument =	
KERNEL SETUP!
Configuration : EvCB	0x16		TCB	0x04
boot file     : cdrom:\SLUS_014.11;1
EXEC:PC0(800129d8)  T_ADDR(80010000)  T_SIZE(001d0000)
boot address  : 800129d8 801fff00
Execute !
                S_ADDR(801fff00)  S_SIZE()
Change effective memory : 2 MBytes
ResetGraph:jtb=80094620,env=80094668
Got an unknown GPU data word: 00094620
ResetGraph:jtb=80094620,env=80094668
Got an unknown GPU data word: 00094620
PS-X Control PAD Driver  Ver 3.0
Saving memory card memcard1.mcd
Saving memory card memcard2.mcd
CD_init:addr=800937c0
\DATA\WA_MRG.MRG;1 --> 2776
\DATA\SU.MRG;1 --> 3ba
\DATA\MODEL.MRG;1 --> 6f76
\DATA\MOVIE.STR;1 --> 317ee
\DATA\SD_SE.DAT;1 --> 891
\DATA\SD_BGM.DAT;1 --> b78
\DATA\MASTER.XA;1 --> 30cfa
g_SDValue->s_stGlobalHdrSE.s_wSD_NUM_SEGROUP:18
Set SMF Mixer Out:150
CD_init:addr=800937c0
SaveLoadBuf add = 0x801d0000 size = 0x3000
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140
Got an invalid line command...
Got an unknown GPU data word: 00290019
Got an unknown GPU data word: 00290027
Got an unknown GPU data word: 00290023
Got an unknown GPU data word: 00170027
Got an unknown GPU data word: 00170023
Got an unknown GPU data word: 00170015
Got an unknown GPU data word: 00170019
Got an unknown GPU data word: 00080140

**Comment by nicolasnoble** [comment]
Ah ha! Thanks, I'll have a look.
