### ISSUE TITLE
Buggy behavior when running from search bar

### ISSUE THREAD

**Issue by KellanClark** [grumpycoders/pcsx-redux#1358]
### Describe the bug

Running the emulator from the Windows 11 search bar causes a lot of buggy behavior that doesn't happen normally. Here's a short list of what I found using it for a few minutes without trying any games.
- There's always a "Memory card error memcard2.mcd failed to load!" error when I open it
- The popup informing you about the auto-update ability always appears. Selecting either option or manually enabling it in the configuration doesn't make a difference
- Clicking File>Open Disk Image or File>Load binary (I just realized they have inconsistent capitalization) freezes the program for a second or two before the file dialog appears
- Dragging that file dialog to the edge of the screen or expanding the size of it until it reaches an edge crashes the program.

### Expected behavior

When opening the folder and double-clicking on the executable or running it through the command line, everything behaves as normal. There's no error message, auto update works fine, there's no delay after opening the file dialog, and it can be dragged past the edge of the window.

### Steps to reproduce the bug

1. Download the latest Windows 64 bit version from the README
2. Extract the files into a folder
3. In Windows' search bar, type "pcsx" and click the `pcsx-redux.exe` that appears
4. Try to load a file
5. Drag the file browser window to the edge of the screen.

### Operating System

Windows 11

### PCSX-Redux version

Version: 15422.20230709.1.x64
Changeset: 18d5a03e1169b28cf4c48b642bc7dea6fe8eb021
Date & time: 2023-07-09 13:43:59

### CPU model

Intel Core i9-13900HX

### GPU model & Drivers

Renderer: NVIDIA GeForce RTX 4080 Laptop GPU/PCIe/SSE2  Version: 3.2.0 NVIDIA 528.66

### BIOS version

N/A

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

**Comment by nicolasnoble** [comment]
#1359 should fix it.

**Comment by nicolasnoble** [comment]
Alright, with the next release, settings and all should now be stored by default in the home folder of the current user, which may or may not help with this sort of problems. Let me know if it actually does.

**Comment by KellanClark** [comment]
It fixed the memory card error and auto update. Opening the file dialogs still has that weird delay and you can't drag/expand them past the end of the main window without crashing.

**Comment by nicolasnoble** [comment]
Thanks for testing and letting me know. This is definitely bizarre. I wonder what could be the cause here.

**Comment by KellanClark** [comment]
Fixed by #1378
