### ISSUE TITLE
PCSX Redux issues for macOS

### ISSUE THREAD

**Issue by spotanjo3** [grumpycoders/pcsx-redux#1362]
My macOS is: 

MacBook Pro Retina 13 inches Mid 2014
Processor 2.6 GHZ Dual-Core Intel Core i5
Memory 8 GB 1600 MHz DDR3
Graphics Intel Iris 1538 MB

When I double clicked it to opened PCSX Redux and I got the message:

“PCSX-Redux” can’t be opened because Apple cannot check it for malicious software.

I closed it and reopen it again by right button of mouse and click Open. it didn't showing anything. Nothing on my monitor! 

Yes, I followed your instruction at: https://github.com/grumpycoders/pcsx-redux and it is not in my security and privacy list at all.

**Comment by nicolasnoble** [comment]
What version of MacOS?

**Comment by spotanjo3** [comment]
Hi. Sorry, I forgot. It is macOS Big Slur. ^_^

**Comment by spotanjo3** [comment]
Hello?

**Comment by nicolasnoble** [comment]
MacOS Big Sur is version 11. The github action builder is using MacOS Monterey, which is version 12. I'm guessing this may have something to do with it.

**Comment by spotanjo3** [comment]
Yeah, I guess so. Is there a way you can added version 11 ? I would be happy to test it for you. I have a Windows Laptop and it works great. I would like to test on macOS version 11 as well.

**Comment by wheremyfoodat** [comment]
> Can I test with downgrade macOS version of 11 now?

Yes please, try it out and tell us if it works.

**Comment by spotanjo3** [comment]
Sure but I only see May 12 2023 released. *scratch my head* ^_^;

**Comment by wheremyfoodat** [comment]
Microsoft App Center sorts by version number by default (ie git commit hash), instead of most recent version
Change this menu to "most recent"

![image](https://github.com/grumpycoders/pcsx-redux/assets/44909372/015f6e7a-bfc6-4680-9a33-1cb6a8d212e6)

**Comment by spotanjo3** [comment]
Oh I didn't know that. I just get out of macOS in other room and test it. Good news: It works fine now on Version 11! Thank you so much! Now, Windows Laptop and macOS Laptop are working! :D

**Comment by wheremyfoodat** [comment]
Yay!
