### ISSUE TITLE
[macOS] Info.plist missing most important values including the 'bundle identifier'

### ISSUE THREAD

**Issue by core-code** [grumpycoders/pcsx-redux#1398]
### Describe the bug

the Info.plist file misses most important and required values and its not clear to me why the app can even be launched without the CFBundleExecutable key.

adding this to ```scripts/create-app.sh``` should fix most issues, including the missing bundle-identifier:

```
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundleExecutable string PCSX-Redux"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundleDevelopmentRegion string en"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundleInfoDictionaryVersion string 6.0"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundleName string ${APP}"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundlePackageType string APPL"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add CFBundleIdentifier string net.pcsx.Pcsx-Redux"
PlistBuddy ${APPROOT}/Contents/Info.plist -c "add NSHumanReadableCopyright string Copyright 2023 PCSX-Redux Team"
```

what is still missing is proper version numbers ```CFBundleShortVersionString```&```CFBundleVersion```, but i didn't know where to pull them from

also, ```LSMinimumSystemVersion``` should be set to the official minimum  requirements

### Expected behavior

Info.plist should be valid

### Steps to reproduce the bug

look at Info.plist and compare with Apple develeloper documentation and Xcode's templates

### Operating System

macOS

### PCSX-Redux version

any

### CPU model

N/A

### GPU model & Drivers

N/A

### BIOS version

N/A

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

**Comment by nicolasnoble** [comment]
Feel free to send a pull request? We have no idea how macos works, honestly.

**Comment by core-code** [comment]
i already sent the 7 additional lines, if a useful change cannot be applied without PR, then let's keep it broken.

**Comment by wheremyfoodat** [comment]
> i already sent the 7 additional lines, if a useful change cannot be applied without PR, then let's keep it broken.

Well, neither Nicolas nor I can add the rest of the plist & test the app bundle since we do not have a Mac and aren't really interested in buying one

That "if a useful change cannot be applied without PR, then let's keep it broken" mentality is certainly interesting, on Github of all platforms. Definitely a new one.

**Comment by core-code** [comment]
> nor I can add the rest of the plist & test the app bundle since we do not have a Mac 

will you be able to test it if a PR is sent?

>  Definitely a new one.

nope a very old one. we've sent patch files long before GitHub and friends existed. it is the PR overhead that is "new"...

**Comment by wheremyfoodat** [comment]
> will you be able to test it if a PR is sent?

No, but at least someone will have tested

**Comment by nicolasnoble** [comment]
> will you be able to test it if a PR is sent?
The point of a PR is basically assuming that its author has done some amount of testing themselves. It's basically a moral contract that says "here, I've done this exact change here on my computer, it worked for me, and the rest of the community can take the change verbatim." 

Since nobody here has a Mac, us sending a PR would violate this moral contract by pushing a change blindly.

**Comment by core-code** [comment]
i have not tested the PR in any way and i have no further time to contribute.

**Comment by nicolasnoble** [comment]
Good talk.
