### ISSUE TITLE
psyqo PAL not centered.

### ISSUE THREAD

**Issue by the-connors** [grumpycoders/pcsx-redux#1405]
Using psyqo example code on PAL 5552 machine, screen cut on top, and black on bottom.

Code:
```c++
    psyqo::GPU::Configuration config;
    config.set(psyqo::GPU::Resolution::W320)
        .set(psyqo::GPU::VideoMode::AUTO)
        .set(psyqo::GPU::ColorMode::C15BITS)
        .set(psyqo::GPU::Interlace::PROGRESSIVE);
    gpu().initialize(config);
```

Output:
![image](https://github.com/grumpycoders/pcsx-redux/assets/131186408/2c975ab3-6560-4a0f-b6a9-cbacbddae59a)

https://github.com/ps-iowned/loader-beta-test/issues/2

Report: @danhans42.

**Comment by nicolasnoble** [comment]
Alright, I'm going to need some help with this one. I have a PAL console on which I tested this code, and my capture card doesn't show any problem. Tho I might be able to find some old screen to test with and find the right settings. 

@danhans42? @JonathanDotCel?

**Comment by danhans42** [comment]
@nicolasnoble - no worries - got a few different PAL receivers and setups I can test on. Feel free to throw any tests my way

**Comment by nicolasnoble** [comment]
This was address.
