### ISSUE TITLE
Bug in ps1-packer & openbios cart?

### ISSUE THREAD

**Issue by the-connors** [grumpycoders/pcsx-redux#1406]
openbios cart boot:
https://github.com/grumpycoders/pcsx-redux/blob/6f6576fa049038d1820419bb245c28273b2c727a/src/mips/openbios/boot/boot.s#L223-L228

ps1-packer:
https://github.com/grumpycoders/pcsx-redux/blob/6f6576fa049038d1820419bb245c28273b2c727a/src/supportpsx/ps1-packer.cc#L146-L151

This set DCIC before BDA / BDAM. But BDA / BDAM maybe not proper and trigger breakpoint? Maybe better order:

```
DCIC = 0
BDA = address
BDAM = addressmask
DCIC = mask
```
make sure breakpoint won't trigger.

**Comment by nicolasnoble** [comment]
Okay, you had my curiosity with #1400 and #1405, but now you've got my attention :-)

DCIC is supposed to be zeroed by the BIOS on boot, so technically the boot.s file is correct.

However, ps1-packer is intended to produce payloads usable in many situations, so this concern is probably legit. I'll adjust the code accordingly.

**Comment by nicolasnoble** [comment]
This was addressed.
