### ISSUE TITLE
openbios not booting SCEE cdrom image

### ISSUE THREAD

**Issue by gwald** [grumpycoders/pcsx-redux#1430]
### Describe the bug

SCEE CDROM images created via https://archive.org/details/net-yaroze-dev-winxp-vm-2022 (dino demo included created from that VM). 

Looks hacky, it uses the official DOS tools then patched with a 36k binary, but it seems to work on other emulators I've tried, including PCSX-redux with an official Sony bios.
So, I'm not sure if it's helpful to the OpenBios project.

[psx-iso.zip](https://github.com/grumpycoders/pcsx-redux/files/12502655/psx-iso.zip)

### Expected behavior

CDROM boot, and see the original Sony Dino demo.
![image](https://github.com/grumpycoders/pcsx-redux/assets/4924613/3e34ee1b-4510-479d-8684-8c0933bf0f1e)

### Steps to reproduce the bug

C:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\grumpycoders.psx-dev\pcsx-redux\pcsx-redux.exe -iso psx.iso -run -bios C:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\grumpycoders.psx-dev\pcsx-redux\openbios.bin

stops at :(

![image](https://github.com/grumpycoders/pcsx-redux/assets/4924613/30fb1d6b-4a73-4830-95b7-1ab7780e15da)

using something like:
-bios bios\SCPH101.BIN
Works fine.

### Operating System

Windows 10

### PCSX-Redux version

![image](https://github.com/grumpycoders/pcsx-redux/assets/4924613/b449346e-b7ae-4746-8d90-4dd768744d6f)
16083.20230827.8.x64

GL info
![image](https://github.com/grumpycoders/pcsx-redux/assets/4924613/5f946f0d-34a0-4728-81bc-0a3bc19896d8)

### CPU model

i7 in VMWare

### GPU model & Drivers

SVGA3D GL4.3

### BIOS version

OpenBios

### Options

- [X] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

### Iso checks

redump.org looks down?
But iso, with a .cue and renamed to psx.bin works with other emulators including mednafen.

### Logs

Loading memory card C:\Users\Administrator\AppData\Roaming\pcsx-redux\memcard1.mcd
Loading memory card C:\Users\Administrator\AppData\Roaming\pcsx-redux\memcard2.mcd
Warning: OpenGL error reporting disabled. See About dialog for more information.
Loaded CD Image: psx.iso.
Track 01 (DATA) - Start 00:02:00, Length 04:11:56
CD-ROM Label: PSX
CD-ROM ID: 
CD-ROM EXE Name: SCE_XPVM.NYE;1
PCSX-Redux booting
Copyright (C) 2019-2023 PCSX-Redux authors
CPU type: Dynarec (x86-64)
Loaded BIOS: C:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\grumpycoders.psx-dev\pcsx-redux\openbios.bin
OpenBIOS detected (caf3bea7)
================
uC-sdk - booting
================
BIOS Trace1: 0x0f
BIOS Trace1: 0x0e
BIOS Trace1: 0x01
BIOS Trace1: 0x02
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x01
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x05
BIOS Trace1: 0x06
BIOS Trace1: 0x02
BIOS Trace1: 0x05
PS-X Realtime Kernel OpenBios - build id 230da32ee85c22ab8b51cfbfd2e788b68f19825b.
Copyright (C) 2019-2023 PCSX-Redux authors.
BIOS Trace1: 0x06
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
BIOS Trace1: 0x07
*** OpenBIOS tiny shell - starting ***
80030cd4 [CDROM] Command: CdlUnknown(0x0A)
80032834 [CDROM][Delayed] Command: CdlUnknown(0x0A)
80030e10 [CDROM] Command: CdlUnknown(0x0A)
80030d9c [CDROM][Delayed] Command: CdlUnknown(0x0A)
80030e10 [CDROM] Command: CdlGetTN (returns 1)
80030e10 [CDROM] Command: CdlUnknown(0x1A)
80031670 [CDROM][Delayed] Command: CdlUnknown(0x1A)
80031024 [CDROM] Command: CdlSetmode 00 (DATA 2048bytes @1x)
800312ec [CDROM] Command: CdlSetloc 00:02:16
80030e10 [CDROM] Command: CdlUnknown(0x06)
80030c40 [CDROM] Command: CdlUnknown(0x09)
80030d9c [CDROM][Delayed] Command: CdlUnknown(0x09)
80031190 [CDROM] Command: CdlSetloc 00:02:22
80030e10 [CDROM] Command: CdlUnknown(0x06)
80030c40 [CDROM] Command: CdlUnknown(0x09)
80030f08 [CDROM][Delayed] Command: CdlUnknown(0x09)
*** Data is acceptable, booting now. ***
BIOS Trace1: 0x08
000016dc [CDROM] Command: CdlUnknown(0x0A)
000016dc [CDROM] Command: CdlUnknown(0x0A)
00001730 [CDROM][Delayed] Command: CdlUnknown(0x0A)
00001374 [CDROM] Command: CdlSetloc 00:02:16
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
bfc05950 [CDROM][Delayed] Command: CdlUnknown(0x09)
00001374 [CDROM] Command: CdlSetloc 00:02:18
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
bfc05950 [CDROM][Delayed] Command: CdlUnknown(0x09)
BOOTSTRAP LOADER
BIOS Trace1: 0x09
000013e8 [CDROM] Command: CdlUnknown(0x01)
00001374 [CDROM] Command: CdlSetloc 00:02:22
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
bfc05950 [CDROM][Delayed] Command: CdlUnknown(0x09)
setup file    : cdrom:SYSTEM.CNF;1
000013e8 [CDROM] Command: CdlUnknown(0x01)
00001374 [CDROM] Command: CdlSetloc 00:02:16
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
bfc05988 [CDROM][Delayed] Command: CdlUnknown(0x09)
00001374 [CDROM] Command: CdlSetloc 00:02:18
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
bfc05950 [CDROM][Delayed] Command: CdlUnknown(0x09)
00001374 [CDROM] Command: CdlSetloc 04:11:55
00000be4 [CDROM] Command: CdlUnknown(0x15)
000014dc [CDROM] Command: CdlSetmode 80 (DATA 2048bytes @2x)
00000be4 [CDROM] Command: CdlUnknown(0x06)
000008e0 [CDROM] Command: CdlUnknown(0x09)
000000b0 [CDROM][Delayed] Command: CdlUnknown(0x09)
BOOT =	cdrom:\SCE_XPVM.NYE;1 
argument =	
KERNEL SETUP!
Configuration : EvCB	0x00		TCB	0x00
boot file     : cdrom:\SCE_XPVM.NYE;1 
000013e8 [CDROM] Command: CdlUnknown(0x01)

Then stop, with kernal calls:

KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc031d8
KernelCall B0:0B:testEvent(0xffffffff {, }) from 0xbfc03188

repeating forever.

**Comment by gwald** [comment]
I'm not 100% it's a valid CDROM image

**Comment by nicolasnoble** [comment]
I just tried with the latest version of OpenBIOS. This worked properly. Are you using the latest version?

**Comment by gwald** [comment]
Hi Nicolas, I installed by following your most excellent video :)
Also, I found the problem, it was the .cnf file... it looks like there's spaces before new lines, I'm guess it was that.

From:
`BOOT=cdrom:\SCE_XPVM.NYE;1 
TCB=4 
EVENT=10 
STACK=801ffff0 
 				  
`

To:
`BOOT = cdrom:\SCE_XPVM.NYE;1
TCB = 4
EVENT = 16
STACK = 801ffff0
`

**Comment by nicolasnoble** [comment]
Hah, yep, I recently fixed some bugs in the system.cnf parser related to trailing spaces.

If you're using the vscode extension, you can always install the latest version using the "Install" button again.

**Comment by gwald** [comment]
Great! thanks for the tip

**Comment by gwald** [comment]
Worked :)
Thanks for that!

**Comment by nicolasnoble** [comment]
Yay, glad to hear that :)
