### ISSUE TITLE
"Break on execution map" breaks on already-executed code

### ISSUE THREAD

**Issue by ItEndsWithTens** [grumpycoders/pcsx-redux#1454]
### Describe the bug

When playing the original NA release of Silent Hill, after using the "Map execution" option and running the game for a while, enabling "Break on execution map" causes the debugger to break immediately. It breaks regardless of how long "Map execution" has been enabled (e.g. 30 seconds or 10 minutes), and always on the same address (inside an ISR, with a base of 0xbfc).

### Expected behavior

When enabling "Break on execution map" the debugger should not break on code that has already been executed.

### Steps to reproduce the bug

1. Load a disc image of the original 1.0 NA release of Silent Hill, start a new game, and skip the intro cinematic and cutscene until the letterbox fades away and you're given control of the game.
2. Ensure the debugger is enabled, and in the Debug|CPU menu, enable the Breakpoints window. Check the "Map execution" box and wait 30 seconds or so.
3. Check the "Break on execution map" box and the debugger will immediately break on an address with a base of 0xbfc.
4. Uncheck "Break on execution map", resume emulation, and wait a while longer with "Map execution" still enabled.
5. Check "Break on execution map" and the debugger will once again immediately break, on the same address as before, despite that code having already been executed.

### Operating System

Windows 10 22H2 (build 19045.3448)

### PCSX-Redux version

Built from source at commit 755ec00.

I first saw the problem when using the currently most recent nightly:
Version: 16526.20231007.2.x64
Changeset: 755ec00749d8b22caa57644f0a8536a381fb9e66
Date & time: 2023-10-07 01:29:34

### CPU model

Intel Xeon E3-1275L v3

### GPU model & Drivers

AMD RX 580 w/Adrenalin 23.9.2 drivers

### BIOS version

OpenBIOS

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [X] Debugger

### Iso checks

The CRC-32 is calculated as 1d4a3ff7, which matches [what's reported on Redump](http://redump.org/disc/137/).

### Logs

Loading memory card memcard1.mcd
Loading memory card memcard2.mcd
Warning: OpenGL error reporting disabled. See About dialog for more information.
PCSX-Redux booting
Copyright (C) 2019-2023 PCSX-Redux authors
CPU type: Interpreted
Loaded BIOS: D:\Development\pcsx-redux\src\mips\openbios\openbios.bin
OpenBIOS detected (c1fac400)
Loaded CD Image: D:\Projects\Games\Silent Hill\CloneCD\SilentHill-Jan-1-2020.img[+cue][+sub].
Track 01 (DATA) - Start 00:02:00, Length 58:14:65
CD-ROM Label: 
CD-ROM ID: SLUS00707
CD-ROM EXE Name: SLUS_007.07;1

uC-sdk - booting

BIOS Trace1: 0x0f
BIOS Trace1: 0x0e
BIOS Trace1: 0x01
BIOS Trace1: 0x02
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x01
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x05
BIOS Trace1: 0x06
BIOS Trace1: 0x02
BIOS Trace1: 0x05
PS-X Realtime Kernel OpenBios - build id unknown.
Copyright (C) 2019-2023 PCSX-Redux authors.
BIOS Trace1: 0x06
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
BIOS Trace1: 0x07
*** OpenBIOS tiny shell - starting ***
*** Data is acceptable, booting now. ***
Breakpoint triggered: PC=0xbfc06304 - Cause:  Execution map

### Additional information

If I may be so bold, I think this is coming from these lines of code:

https://github.com/grumpycoders/pcsx-redux/blob/755ec00749d8b22caa57644f0a8536a381fb9e66/src/core/debug.cc#L44-L45

https://github.com/grumpycoders/pcsx-redux/blob/755ec00749d8b22caa57644f0a8536a381fb9e66/src/core/debug.cc#L55-L56

https://github.com/grumpycoders/pcsx-redux/blob/755ec00749d8b22caa57644f0a8536a381fb9e66/src/core/debug.cc#L70-L71

Shouldn't those 7s be 3s? Both c and 7 include the 4 bit, and what seems to be happening is the address, in my case 0xbfc06304, becomes 0x00406304 after the bitwise AND. That's greater than sizeof(m_biosMemoryMap), i.e. 0x80000, and as such the branch that marks the 0xbfc-based addresses as visited never gets taken.

I'm new to this codebase and I didn't think it was wise to open a PR, since I imagine there could be other wrinkles here that complicate what superficially seems to be a simple solution. Nonetheless I took a stab at the change myself (thank you for the effortless build process, by the way!) and in testing on my own machine it seems to have done the job.

**Comment by nicolasnoble** [comment]
Oops, you're right. This was originally designed for only the main memory. The other maps got added later, and more as an afterthought than anything. The parallel port part is also wrong fwiw. And it's also ignoring the 2/8MB toggle. Surprised this isn't causing more troubles.

**Comment by nicolasnoble** [comment]
Okay so it wasn't as bad as I thought. This was an oversight from the 2/8MB switch, but most everything was fine.

**Comment by ItEndsWithTens** [comment]
That's great, thanks for looking at this! The parallel port and scratchpad stuff escaped me completely; tunnel vision, I guess, I was so focused on what affected me I didn't notice anything else.

I appreciate the fast fix! Can't wait to get back in there and start picking my favorite games apart.

**Comment by nicolasnoble** [comment]
Of course. Let me know how this one goes, or if you need anything.

**Comment by ItEndsWithTens** [comment]
The CI builds are still going right now, but I checked out the code myself and tried it; after a clean rebuild I still notice the problem, and I suspect it's this:

https://github.com/grumpycoders/pcsx-redux/blob/ac329d23621afd8ca2b6dd4e686b7cb6d60daa05/src/core/debug.cc#L76-L78

The array is still being indexed with the old "real" variable. Switching it to "shortReal", just like in the corresponding markMap method, fixes the issue for me.

**Comment by nicolasnoble** [comment]
Derp. I missed this one. Too tired.

**Comment by nicolasnoble** [comment]
The fun part is, it was properly set on the first function, but not the second, and it's even worse now because it's going to do out of bounds reads. Hard-pushed a fix on main directly for it.

**Comment by ItEndsWithTens** [comment]
That did the trick. Got the latest release and I can confirm everything works as expected. Thanks again!
