### ISSUE TITLE
The SLL instruction produced an incorrect result

### ISSUE THREAD

**Issue by kkHAIKE** [grumpycoders/pcsx-redux#1568]
### Describe the bug

<img width="1210" alt="截屏2024-02-16 17 32 59" src="https://github.com/grumpycoders/pcsx-redux/assets/64772/f8ce4d4b-cb0b-4ea8-a753-36c3a11f6fb7">

### Expected behavior

$a1 should be 0x550 instead of 0xf0

### Steps to reproduce the bug

Execute the MIPS code built with clang.

### Operating System

MacOS sonoma

### PCSX-Redux version

Version: 74602094
Changeset: 746020942caec0bb37717b32178a9659606bdc53
Date & time: 2023-12-30 04:01:58

### CPU model

Apple M1

### GPU model & Drivers

Apple M1

### BIOS version

OpenBios

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [X] Fastboot
- [X] Debugger

### Additional information
The code builds into an executable that produces the correct result on my computer, but an odd issue is encountered when running it on pcsx-redus.

**Comment by wheremyfoodat** [comment]
Are you sure the sll is actually executed right before the andi? The chances of sll being wrong are pretty slim since it passes tests and is a trivial operation, and if it didn't work properly nothing would work.

The running program is Twilight Syndrome, right?

**Comment by kkHAIKE** [comment]
I checked, and it seems like the preceding IBU instruction might have a similar delay slot, causing $at to be set after the SLL finishes. But isn't it the case that only branch instructions have delay slots?

**Comment by nicolasnoble** [comment]
If you're building mips I code, please do not use clang. Its support is incomplete at the moment, and it's indeed not supporting all the various hazard cases.

**Comment by wheremyfoodat** [comment]
> I checked, and it seems like the preceding IBU instruction might have a similar delay slot, causing $at to be set after the SLL finishes. clang must be build with load delay

In MIPS I (and not later versions) all memory loads + MFC/CFC have load delay slots and yeah LLVM doesn't fully support them (there's been some progress on it but I'm not sure if that's shipped yet). This means that not only will memory loads have a delay slot, but even reading a GTE register will have one.

**Comment by kkHAIKE** [comment]
Are there any recommended relatively modern compilers available now?

**Comment by nicolasnoble** [comment]
Stock gcc will do. See https://github.com/grumpycoders/pcsx-redux/blob/main/src/mips/psyqo/GETTING_STARTED.md
