### ISSUE TITLE
Toca WTC Will throws error at loading screen

### ISSUE THREAD

**Issue by Johan11235** [grumpycoders/pcsx-redux#1601]
### Describe the bug

Game freezes during loading screen. It tries to jump (JALR) to FFFFFFFF, see log and screenshot.
Using interpreter, EU bios SCPH1002 or SCPH7502, not openbios.
The game is Toca World Touring Cars, SLES_02572 (PAL). It boots and runs fine in ePSXe and NO$PSX.
I have tried the US version, Jarret & Labonte, SLUS_01139, as well as ISO's from other sources, same issue at same address.
I have tried with and without sbi file.
Other games play fine in PCSX-REDUX.
DynaRec throws "unknown instruction for dynarec - address 8000022c, instruction bfc00000"
Short term goal: get the game to run
Long term goal: use PCSX-REDUX with Ghidra and possibly Lua.

### Expected behavior

Expecting the game to run fine.

### Steps to reproduce the bug

Run the ISO with a dumped bios. PAL/NTSC doesent seem to matter.
Openbios will get stuck in a loop somewhere, but not throw error.
Sometimes the settings has to be fiddled with to get to the loading screen, somewhat inconsistently.

### Operating System

Windows 10 Pro 22H2

### PCSX-Redux version

Version: 18254.20240303.1.x64
Changeset: ee9606a92cdb76d9fde3e50593ce8beba60fdc21
Date & time: 2024-03-03 03:15:58

### CPU model

Intel Core i5-4200H

### GPU model & Drivers

GeForce GTX 850M

### BIOS version

EU bios SCPH1002 or SCPH7502, not openbios.

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [X] OpenGL GPU
- [X] Fastboot
- [X] Debugger

### Iso checks

71084ac0 - matches redump

### Logs
Loading memory card C:\Users\Johan\AppData\Roaming\pcsx-redux\memcard1.mcd
Loading memory card C:\Users\Johan\AppData\Roaming\pcsx-redux\memcard2.mcd
Warning: OpenGL error reporting disabled. See About dialog for more information.
PCSX-Redux booting
Copyright (C) 2019-2024 PCSX-Redux authors
CPU type: Interpreted
Loaded BIOS: D:\Spel\Playstation 1\ePSXe205\bios\SCPH7502.bin
Known BIOS detected: SCPH-7502 (EU) (318178bf)
Loaded CD Image: D:\Spel\Playstation 1\PS1 Toca WTC\SLES_02572_TOCA.CUE[+cue]Loaded SBI file: D:\Spel\Playstation 1\PS1 Toca WTC\SLES_02572_TOCA.sbi.
[+sbi].
Track 01 (DATA) - Start 00:02:00, Length 41:30:08
CD-ROM Label: SLES_02572
CD-ROM ID: SLES02572
CD-ROM EXE Name: SLES_025.72;1
BIOS Trace1: 0x0f
BIOS Trace1: 0x0e
BIOS Trace1: 0x01
BIOS Trace1: 0x02
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x01
BIOS Trace1: 0x03
BIOS Trace1: 0x04
BIOS Trace1: 0x05
BIOS Trace1: 0x06
BIOS Trace1: 0x02
BIOS Trace1: 0x05
PS-X Realtime Kernel Ver.2.5
Copyright 1993,1994 (C) Sony Computer Entertainment Inc. 
BIOS Trace1: 0x06
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
BIOS Trace1: 0x07
BIOS Trace1: 0x08
BOOTSTRAP LOADER Type C Ver 2.1   03-JUL-1994
Copyright 1993,1994 (C) Sony Computer Entertainment Inc.
BIOS Trace1: 0x09
setup file    : cdrom:SYSTEM.CNF;1
TCB	00000004
EVENT	00000010
STACK	801fff00
BOOT =	cdrom:\SLES_025.72;1
argument =	
KERNEL SETUP!
Configuration : EvCB	0x10		TCB	0x04
boot file     : cdrom:\SLES_025.72;1
EXEC:PC0(8001b910)  T_ADDR(80010000)  T_SIZE(000fe000)
boot address  : 8001b910 801fff00
Execute !
                S_ADDR(801fff00)  S_SIZE()
Change effective memory : 2 MBytes
CD_init:addr=8004b36c
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
Unknown command for pad: 43
ResetGraph:jtb=8004948c,env=800494d4
Got an unknown GPU data word: 0004948c
32-bit read from unknown address: fffe0130
32-bit write to unknown address: fffe0130
32-bit write to unknown address: fffe0130
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c
Attempted unaligned JALR to 0xffffffff from 0x00000e08, firing exception!
32-bit read from unknown address: 03400010
32-bit read from unknown address: 0340000c

**Comment by nicolasnoble** [comment]
I think I know what's going on. It's probably another bug in the cd-rom subsystem, related to how the game is reading sectors. I'll have to confirm this a bit.

**Comment by nicolasnoble** [comment]
Nope, okay, I know what's going on. Should be a simple fix, but it's led me to discover something we didn't really know about the PS1 until now...

**Comment by Johan11235** [comment]
@nicolasnoble I just poured my morning coffee, fired up my laptop and updated redux, and voila: the game runs! I don’t know exactly what you did but I’m sure I could not have done that myself. 
Thank you very much for looking into this, I appreciate it a lot.

**Comment by nicolasnoble** [comment]
Of course :)
