### ISSUE TITLE
Error showing special symbols

### ISSUE THREAD

**Issue by StanleyKid-22** [grumpycoders/pcsx-redux#1608]
I accidentally noticed during translation (into Ukrainian) that arrows (←↓→↑), action buttons (×■▲●) and other Unicode symbols aren't shown, they are replaced by _"?"_. Somehow I didn't pay attention to this before. Version **18254.20240303.1**.
Is it possible to support such symbols, perhaps in a separate font? If not, then I'll immediately edit the translation and type these symbols in words.
Thanks in advance.

**Comment by nicolasnoble** [comment]
It's totally doable, yes, at least for the proportional font.

Can you give the list of unicode characters you want to add support for?

**Comment by StanleyKid-22** [comment]
I've chosen these:
←: U+2190
↑: U+2191
→: U+2192
↓: U+2193
△: U+25B3
◯: U+25EF
✕: U+2715
☐: U+2610
So far, there was no need for any others.
