### ISSUE TITLE
[Feature request] add support for external video plugins

### ISSUE THREAD

**Issue by LuismaSP89** [grumpycoders/pcsx-redux#1664]
### Describe the bug

First of all, thanks for this awesome emulator and all the effort you're putting in : )

This is not an issue but more a request or question... Is this emulator going to support external plugins like pete's opengl2 tweak and other input or sound plugins? I my humble opinion I think the current default plugins are very limited in therms of enhancements. 

I didn't see a template for opening requests, so my apologies if I did it wrong by opening an issue one.

### Expected behavior

-

### Steps to reproduce the bug

-

### Operating System

-

### PCSX-Redux version

-

### CPU model

-

### GPU model & Drivers

-

### BIOS version

-

### Options

- [ ] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

**Comment by nicolasnoble** [comment]
So, the short answer is "no, we won't do that".

For a longer rationale: getting rid of the plugin system was a conscious decision made very early on, which has benefits that we don't want to rollback:

- A plugin API crystallizes the API between the emulator and the plugins. It means we can't update said API without breaking the plugins. There was already several improvements and bugfixes done by changing said API internally, and there are more planned in the future. No plugins means proper freedom to do these fixes and improvements.
- A random plugin has a state which is opaque to the rest of the emulator. This means that the savestate system can't be reliable with it. The state generated using a certain set of plugins may not load properly within a different set for instance.
- The UX integration of a plugin is dodgy: the configuration window may not be using the same sort of UI elements or design as the rest of the emulator, and the configuration status may also be saved at a different location than the rest of the emulator's configuration, causing a bad UX fragmentation.
- Most of these old plugins are compiled for older versions of operating systems which may not be compatible with the newer codebase. For instance, you're referencing the Pete's plugins, which were 32 bits binaries only, but Redux is a 64 bits one. Having a monolithic codebase means that compiler and operating system updates can be followed in a single homogenous block.
- Testing is more integrated and seamless.

All in all, the plugin system was a good idea way back in the days, where code sharing and distribution had a completely different paradigm. But nowadays, people can simply open a pull request and offer improvements, get it all tested on all platforms in a single pass, and published automatically a few hours later. The advantages of plugin systems simply aren't relevant anymore in today's software landscape.
