### ISSUE TITLE
OpenBIOS: Missing secondary `0xa0` ROM entry for `_bu_init()` syscall handler

### ISSUE THREAD

**Issue by EngineersBox** [grumpycoders/pcsx-redux#1750]
### Describe the bug

The [psx-spx](https://psx-spx.consoledev.net/kernelbios/#a55h-or-a70h-_bu_init) documentation details the `_bu_init()` handler to be located at either `0x55` or `0x70` in the `0xa0` ROM. The current `romA0table` (in `src/mips/openbios/kernel/handlers.c`) only has an entry for `0x70`, meaning any program that invokes `_bu_init()` with a binding that uses an offset of `0x55` will raise an unimplemented syscall exception.

### Expected behavior

This call to `_bu_init()` targeted to `0x55` in the `0xa0` ROM table should succeed, being handled by the same handler as in `0x70` (which is `initBackupUnit` from `src/mips/openbios/card/card.h`)

### Steps to reproduce the bug

1. Bundle the following into a PS1 executable (Use your favourite SDK: PsyQ, PSn00bSDK, etc) as a test call:
```c
inline void bad_bu_init() {
	__asm__ volatile(
		"li $t2, 0xa0\n\t"
		"jr $t2\n\t"
		"li $t1, 0x55"
	);
}
```
2. Invoke the call
3. See that can exception is raised for an unimplemented syscall

### Operating System

MacOS Sonoma 14.5

### PCSX-Redux version

Version: 1abee5ae
Build: 78
Changeset: 1abee5aeaf87d4e288b36333b8f69b7986fe8c03
Date & time: 2024-09-29 15:00:39

### CPU model

Intel i9 9880H @ 2.30GHz

### GPU model & Drivers

AMD Radeon Pro 5500M 8GB

### BIOS version

OpenBIOS

### Options

- [X] Dynarec CPU
- [ ] 8MB
- [ ] OpenGL GPU
- [ ] Fastboot
- [ ] Debugger

**Comment by EngineersBox** [comment]
Right, that's an observation that I haven't confirmed - whether there are any games that use it. My justification was that since the docs had it, someone must have come across a game with it at some stage, otherwise it would be rather strange to have it specified as an alternative.

TBH I'm happy for this to go either way, since the whole reason I raised this was the specific SDK I use (PSn00bSDK) happens to use the `0x55` offset, so happy to just stick with the PR on that and let this be a note more than an issue to fix. However, I do think that given the potential for it to occur *at some stage* might warrant the change? Though I do understand no wanting to set a precedent of accounting for every single potential outlier (that may only ever be a single case).

**Comment by nicolasnoble** [comment]
The documentation has evidently been written by looking at the disassembly of a retail bios. I've been trying to write openbios in a way where I leave holes around all the kernel call tables, and wait for bug reports during the running of games before implementing them, so I can verify my implementation works in-situ. In this case, these are simply aliases, it's not really a big deal for me to add them if I can't verify they work as intended, since the code already works with the other entries, and it's just a normal pointer redirection. I'll do a PR for this later today.
