### ISSUE TITLE
lastest master dont compile on linux

### ISSUE THREAD

**Issue by mrdeathjr28** [grumpycoders/pcsx-redux#196]
lastest master dont compile on linux

hi

in my case show this information in console:

make
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/main/main.o -MF src/main/main.dep src/main/main.cc
In file included from src/main/main.cc:33:
src/gui/gui.h:28:10: fatal error: imgui.h: No existe el archivo o el directorio
   28 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/filedialog.o -MF src/gui/widgets/filedialog.dep src/gui/widgets/filedialog.cc
src/gui/widgets/filedialog.cc:41:10: fatal error: imgui.h: No existe el archivo o el directorio
   41 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/source.o -MF src/gui/widgets/source.dep src/gui/widgets/source.cc
In file included from src/gui/widgets/source.cc:20:
src/gui/widgets/source.h:26:10: fatal error: ImGuiColorTextEdit/TextEditor.h: No existe el archivo o el directorio
   26 | #include "ImGuiColorTextEdit/TextEditor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/assembly.o -MF src/gui/widgets/assembly.dep src/gui/widgets/assembly.cc
src/gui/widgets/assembly.cc:23:10: fatal error: GL/gl3w.h: No existe el archivo o el directorio
   23 | #include <GL/gl3w.h>
      |          ^~~~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/dwarf.o -MF src/gui/widgets/dwarf.dep src/gui/widgets/dwarf.cc
src/gui/widgets/dwarf.cc:26:10: fatal error: fmt/format.h: No existe el archivo o el directorio
   26 | #include "fmt/format.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/types.o -MF src/gui/widgets/types.dep src/gui/widgets/types.cc
src/gui/widgets/types.cc:23:10: fatal error: imgui.h: No existe el archivo o el directorio
   23 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/registers.o -MF src/gui/widgets/registers.dep src/gui/widgets/registers.cc
src/gui/widgets/registers.cc:20:10: fatal error: imgui.h: No existe el archivo o el directorio
   20 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/breakpoints.o -MF src/gui/widgets/breakpoints.dep src/gui/widgets/breakpoints.cc
src/gui/widgets/breakpoints.cc:20:10: fatal error: imgui.h: No existe el archivo o el directorio
   20 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/log.o -MF src/gui/widgets/log.dep src/gui/widgets/log.cc
In file included from src/gui/widgets/log.cc:21:
src/gui/widgets/log.h:24:10: fatal error: imgui.h: No existe el archivo o el directorio
   24 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/vram-viewer.o -MF src/gui/widgets/vram-viewer.dep src/gui/widgets/vram-viewer.cc
src/gui/widgets/vram-viewer.cc:27:10: fatal error: GL/gl3w.h: No existe el archivo o el directorio
   27 | #include "GL/gl3w.h"
      |          ^~~~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/gui.o -MF src/gui/gui.dep src/gui/gui.cc
In file included from src/gui/gui.cc:21:
src/gui/gui.h:28:10: fatal error: imgui.h: No existe el archivo o el directorio
   28 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gpu/soft/prim.o -MF src/gpu/soft/prim.dep src/gpu/soft/prim.cc
src/gpu/soft/prim.cc:89:10: fatal error: imgui.h: No existe el archivo o el directorio
   89 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gpu/soft/draw.o -MF src/gpu/soft/draw.dep src/gpu/soft/draw.cc
src/gpu/soft/draw.cc:103:10: fatal error: GL/gl3w.h: No existe el archivo o el directorio
  103 | #include "GL/gl3w.h"
      |          ^~~~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/core/pad.o -MF src/core/pad.dep src/core/pad.cc
src/core/pad.cc:22:10: fatal error: imgui.h: No existe el archivo o el directorio
   22 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/spu/cfg.o -MF src/spu/cfg.dep src/spu/cfg.cc
src/spu/cfg.cc:20:10: fatal error: imgui.h: No existe el archivo o el directorio
   20 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
g++ `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/spu/debug.o -MF src/spu/debug.dep src/spu/debug.cc
src/spu/debug.cc:21:10: fatal error: imgui.h: No existe el archivo o el directorio
   21 | #include "imgui.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** No hay ninguna regla para construir el objetivo 'src/spu/debug.dep', necesario para 'dep'.  Alto.

maybe add more information about compiling can help

**Comment by nicolasnoble** [comment]
Hah! Sorry I didn't notice this beforehand.

So for compiling under Linux, I highly recommend using Docker, and I'm providing an image for it. Please check the `dockermake.sh` script at the repository's root. Simply running that script should produce a `pcsx-redux` binary. The `Dockerfile` also should provide information about which packages are required to install.

Last but not least you need to clone using submodules for this to work, so run `git submodule update --init --recursive`.

**Comment by mrdeathjr28** [comment]
hi

i use docker as youre said but still dont work:

show this on console:

sudo ./dockermake.sh
[sudo] contraseña para linuxdesktopx86: 
latest: Pulling from grumpycoders/pcsx-redux-build
Digest: sha256:562861ac976c9c945ddb0abce308c3517c10dedb74af384322d9ca16ec835ccb
Status: Image is up to date for grumpycoders/pcsx-redux-build:latest
docker.io/grumpycoders/pcsx-redux-build:latest
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/main/main.o -MF src/main/main.dep src/main/main.cc
In file included from src/main/main.cc:33:
src/gui/gui.h:28:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/filedialog.o -MF src/gui/widgets/filedialog.dep src/gui/widgets/filedialog.cc
src/gui/widgets/filedialog.cc:41:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/source.o -MF src/gui/widgets/source.dep src/gui/widgets/source.cc
In file included from src/gui/widgets/source.cc:20:
src/gui/widgets/source.h:26:10: fatal error: 'ImGuiColorTextEdit/TextEditor.h' file not found
#include "ImGuiColorTextEdit/TextEditor.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/assembly.o -MF src/gui/widgets/assembly.dep src/gui/widgets/assembly.cc
src/gui/widgets/assembly.cc:23:10: fatal error: 'GL/gl3w.h' file not found
#include <GL/gl3w.h>
         ^~~~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/dwarf.o -MF src/gui/widgets/dwarf.dep src/gui/widgets/dwarf.cc
src/gui/widgets/dwarf.cc:26:10: fatal error: 'fmt/format.h' file not found
#include "fmt/format.h"
         ^~~~~~~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/types.o -MF src/gui/widgets/types.dep src/gui/widgets/types.cc
src/gui/widgets/types.cc:23:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/registers.o -MF src/gui/widgets/registers.dep src/gui/widgets/registers.cc
src/gui/widgets/registers.cc:20:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/breakpoints.o -MF src/gui/widgets/breakpoints.dep src/gui/widgets/breakpoints.cc
src/gui/widgets/breakpoints.cc:20:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/log.o -MF src/gui/widgets/log.dep src/gui/widgets/log.cc
In file included from src/gui/widgets/log.cc:21:
src/gui/widgets/log.h:24:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/widgets/vram-viewer.o -MF src/gui/widgets/vram-viewer.dep src/gui/widgets/vram-viewer.cc
src/gui/widgets/vram-viewer.cc:27:10: fatal error: 'GL/gl3w.h' file not found
#include "GL/gl3w.h"
         ^~~~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gui/gui.o -MF src/gui/gui.dep src/gui/gui.cc
In file included from src/gui/gui.cc:21:
src/gui/gui.h:28:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gpu/soft/prim.o -MF src/gpu/soft/prim.dep src/gpu/soft/prim.cc
src/gpu/soft/prim.cc:89:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/gpu/soft/draw.o -MF src/gpu/soft/draw.dep src/gpu/soft/draw.cc
src/gpu/soft/draw.cc:103:10: fatal error: 'GL/gl3w.h' file not found
#include "GL/gl3w.h"
         ^~~~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/core/pad.o -MF src/core/pad.dep src/core/pad.cc
src/core/pad.cc:22:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/spu/cfg.o -MF src/spu/cfg.dep src/spu/cfg.cc
src/spu/cfg.cc:20:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
clang++-9 `pkg-config --cflags glfw3 libavcodec libavformat libavutil libswresample libuv sdl2 zlib` -Isrc -Ithird_party -Ithird_party/fmt/include/ -Ithird_party/googletest/googletest/include -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples -Ithird_party/imgui/misc/cpp -Ithird_party/imgui_club -Ithird_party/libelfin -Ithird_party/zstr/src -g -O3 -std=c++2a -M -MT src/spu/debug.o -MF src/spu/debug.dep src/spu/debug.cc
src/spu/debug.cc:21:10: fatal error: 'imgui.h' file not found
#include "imgui.h"
         ^~~~~~~~~
1 error generated.
make: *** No rule to make target 'src/spu/debug.dep', needed by 'dep'.  Stop.

**Comment by nicolasnoble** [comment]
That's because you pulled without the submodules.

Run this once: `git submodule update --init --recursive`

**Comment by mrdeathjr28** [comment]
solved apparently git have troubles in my machine, add third tools in each folder and works
