### ISSUE TITLE
error: cannot initialize a parameter of type 'const char *' with an lvalue of type 'int'

### ISSUE THREAD

**Issue by wodinga** [grumpycoders/pcsx-redux#261]
Getting this error when building on MacOS Catalina.

`third_party/zstr/src/strict_fstream.hpp:39:36: error: cannot initialize a parameter of type 'const char *' with an lvalue of type 'int'`

**Comment by nicolasnoble** [comment]
There's a patch in the repository for this one. That's temporary until I get rid of zstr.

https://github.com/grumpycoders/pcsx-redux/blob/main/.github/zstr_strict_fstream_darwin_fix.patch
