### ISSUE TITLE
Won't run on OpenGL 3.1 GPU

### ISSUE THREAD

**Issue by tomasz-rozanski** [grumpycoders/pcsx-redux#272]
I'm trying to run the emulator on Lenovo Thinkpad x220 with Intel HD3000 GPU, which supports OpenGL 3.1. I'm getting the following error message:
```console
Glfw Error 65543: WGL: OpenGL profile requested but WGL_ARB_create_context_profile is unavailable
Assertion failed: m_window, file d:\a\1\s\src\gui\gui.cc, line 106
```

I'm using:
- Windows 10 Pro (ver 2004, 19041.388)
- pcsx-redux-nightly-1441.20200719.2-x64

**Comment by nicolasnoble** [comment]
So I'm not really an expert on OpenGL things, quite the contrary. As a result, I've been trying to stick to what I've been told is "best practice" of using OpenGL Core Profile so I don't use any feature by mistake that I shouldn't be using.

Unfortunately, while my code technically only requires OpenGL 3.0, the notion of profiles is only available in OpenGL 3.2, and I don't necessarily want to lose this aspect of the spec.

But I don't mind trying to get the code to fallback on OpenGL 3.0 if it couldn't create a 3.2 context. At this point it'd mean that the user would be on their own if the code fallbacks to 3.0 and I'm accidentally using something that really requires 3.2.

#275 is going to try addressing this, but I obviously don't have much means to test it. I'll leave this issue opened so you can try with the new build and close the issue yourself if it fixes it.

**Comment by teorex3** [comment]
not run latest build with OGL 3.3 (nvidia geforce 9600 GT)
log message:
0(2): warning C7568: version 300 not fully supported on current GPU target profile,
Vertex info:
0(2): warning C7568: version 300 not fully supported on current GPU target profile,
Fragment info:
0(2): warning C7568: version 300 not fully supported on current GPU target profile,

**Comment by lorn10** [comment]
Okay folks, here follows now a little additional information to that topic.

In short, at least for @tomasz-rozanski, these problems may be OpenGL **driver related**. Yes, the Intel HD 3000 series hardware is OpenGL 3.3 compatible but the Windows driver aren't at this level, - they are limited to **OpenGL 3.1**. The bad thing is that Intel will **not update them**. This is true for the whole 6th Generation iGPU series, the Intel HD and Intel HD 2000 Graphics.

Well, this is not true for Linux and Mac OS where both OS expose on the exact same Intel hardware **full OpenGL 3.3 support** also from the driver side. :-) The Linux Intel MESA drivers are furthermore in GREAT condition, - they are proven to be stable, compatible and fast. On Windows the OpenGL drivers are unfortunately quite often bad and incomplete, this seems true for AMD and mostly also Intel.

More information about the **Intel OpenGL GPU hardware and software** support can be found here:
https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen6

Finally, the only solution to get really good OpenGL driver support on that old Intel hardware here is to install a Linux OS like Kubuntu. It is not necessary to kill Windows 10 completely, it is also possible to config a dual boot system. ;-)

**Comment by lorn10** [comment]
Just for reference, - I can definitely confirm, PCSX-Redux works perfectly well at an **Intel HD 2000** "Sandy Bridge" iGPU in conjunction with the brand new Mesa Gallium 3D "**Crocus**" driver under Kubuntu 20.04 LTS. :+1: This driver provides full OpenGL 3.3 support.

And this is true despite the fact that currently no 3D hardware acceleration is available in PCSX-Redux. The frame rate is not enormous, though. But it is still around playable 80 - 100 fps while it is at my AMD Radeon (TURKS based) HD 6770M around 800 to 1000 fps. ;-)
