### ISSUE TITLE
Parasite Eve Disc 1 hangs on boot in PCSX-Redux

### ISSUE THREAD

**Issue by VirtuaCop** [grumpycoders/pcsx-redux#332]
When Loading Parasite Eve in PCSX-Redux, the game hangs on boot to black screen.
Configuration : EvCB	0x16		TCB	0x04
boot file     : cdrom:\SLUS_006.62;1
EXEC:PC0(80072534)  T_ADDR(80010000)  T_SIZE(001ee000)
boot address  : 80072534 801fff00
Execute !

                S_ADDR(801fff00)  S_SIZE(00000000)
ResetGraph:jtb=80095704,env=8009574c
Found C0 patch hash 099be910 "_patch_gte#1", issued from 0x8007a154, executing...
Found C0 patch hash 17374c76 "_patch_card#2", issued from 0x8007e3fc, executing...
Found B0 patch hash c29df18f "_patch_card2#2", issued from 0x8007e490, executing...
addr=8009b298

**Comment by wheremyfoodat** [comment]
Have tested that this works after the immense pain #786 caused me.
