### ISSUE TITLE
Yu-Gi-Oh! Forbidden Memories (USA) hangs on load with openbios 

### ISSUE THREAD

**Issue by VirtuaCop** [grumpycoders/pcsx-redux#335]
possible memcard access issue

Loaded BIOS: openbios.bin
Loaded CD Image: D:\psx\New folder (2)\Yu-Gi-Oh! Forbidden Memories (USA).cue[+cue].

Execute !
                S_ADDR(801fff00)  S_SIZE(00000000)
Change effective memory : 2 MBytes
Found C0 patch hash 099be910 "_patch_gte#1", issued from 0x80089b40, executing...
Found B0 patch hash cef165ba "_remove_ChgclrPAD#1", issued from 0x80074120, executing...
Found B0 patch hash f803a6a6 "_patch_pad#1", issued from 0x80074098, executing...
PS-X Control PAD Driver
Found C0 patch hash 17374c76 "_patch_card#2", issued from 0x8008b60c, executing...
Found B0 patch hash c29df18f "_patch_card2#2", issued from 0x8008b6a0, executing...
Found B0 patch hash 5123f82a "_patch_card_info#1", issued from 0x8008b528, executing...

**Comment by johnbaumann** [comment]
This game appears to be working now with the latest version of Redux+OpenBIOS. This issue is pretty old so I'll go ahead and close. Please feel free to re-open this issue if you continue to experience the issue.
