### ISSUE TITLE
File Browser - Date

### ISSUE THREAD

**Issue by danhans42** [grumpycoders/pcsx-redux#502]
Not sure if this is a bug as such..

The file browser seems to show the date/time a file was created under Date/Time. 
Cheeky ask - would it be possible to change this to the modified time?

Build info : https://install.appcenter.ms/orgs/grumpycoders/apps/pcsx-redux-linux64/distribution_groups/public
OS:  Linux Mint 20 Cinnamon (AMD64)

**Comment by danhans42** [comment]
![sshot](https://user-images.githubusercontent.com/15861619/121049921-1119b100-c7b0-11eb-9f7f-ab79fc773c06.png)

**Comment by nicolasnoble** [comment]
So unfortunately, the timestamp I'm getting is supposed to be [last write time](https://en.cppreference.com/w/cpp/filesystem/last_write_time). I think it means there's a bug somewhere in the standard library?

**Comment by nicolasnoble** [comment]
Should've been fixed :)
