### ISSUE TITLE
pcsx-redux.exe doesn't start on Windows (VirtualBox 6.1). Glfw Error 65532

### ISSUE THREAD

**Issue by hercc82** [grumpycoders/pcsx-redux#525]
Hi, 

I am trying to run pcsx-redux.exe but it fails.

System:
- pcsx-redux-nightly-4470.20210615.8-x64
- Windows 10, 20H2, 19042.1052, Running on VirtualBox 6.1
- VirtualBox Graphics Adapter

Error:
Glfw Error 65532: WGL: The driver does not appear to support OpenGL

Is my problem maybe related to this issue? https://github.com/grumpycoders/pcsx-redux/issues/272
Do I understand correctly that your programme requires a system with OpenGL 3.3? The OpenGL Extension Viewer prints 6.0.14.0 as OpenGL on my System. I do not know if that makes any difference to you. 

What would be the solution?

BTW this crash isn't use friendly because although running from cmd the new window containing this error disappears very quickly. Better error handling would be nice.

**Comment by wheremyfoodat** [comment]
Can you show us your GPU virtualization settings and tell us if you've got GPU pass-through or something of the sort enabled? Also your GPU model (and CPU if it's an iGPU)

As for the latter - if you execute Redux from a shell the window won't disappear after crashes, so you'll be able to see errors fine

**Comment by nicolasnoble** [comment]
> As for the latter - if you execute Redux from a shell the window won't disappear after crashes, so you'll be able to see errors fine

I suspect the wrapper is making it no longer the case.

**Comment by hercc82** [comment]
GeForce GTX 960 is my GPU. NVIDIA Driver Version 460.67 for linux 64 bit. 

See attachment for my VM Display config. I have tried VBoxSVGA as well as VBoxVGA as a Graphics Controller.
![vm_display](https://user-images.githubusercontent.com/69757093/122983100-e9277180-d39b-11eb-81ed-5e3582d7f3a8.png)

The complete error:
Glfw Error 65532: WGL: The driver does not appear to support OpenGL
Glfw Error 65532: WGL: The driver does not appear to support OpenGL
Assertion failed: m_window, file D:\a\1\s\src\gui\gui.cc, line 244

>As for the latter - if you execute Redux from a shell the window won't disappear after crashes, so you'll be able to see errors fine

I am executing Redux from Windows Command Prompt but then a new window opens and is closed very quickly.

**Comment by hercc82** [comment]
I can run PS2 games on the same VM on PCSX2 without problems. Maybe this information will help to draw any conclusions.... Furthermore I was able to run PCSX-Redux on the same machine on native Windows (no VM). Anyway, it would be nice to know what is the problem with my VM.

**Comment by wheremyfoodat** [comment]
@hercc82 Have you tried ticking the "Enable 3D acceleration" button in VirtualBox (pictured below) and running the emulator, to see if it works?
![image](https://user-images.githubusercontent.com/44909372/123141037-9cf23500-d460-11eb-87e1-93d3dbe926e2.png)

**Comment by nicolasnoble** [comment]
The other question I have would be why are you trying to run pcsx-redux in a virtualbox machine?

**Comment by hercc82** [comment]
>Have you tried ticking the "Enable 3D acceleration" button in VirtualBox (pictured below) and running the emulator, to see if it works?

@wheremyfoodat I am trying. pcsx-redux still crashes. The error is a bit different now.

>Glfw Error 65543: WGL: Failed to create OpenGL context

@nicolasnoble There can be many reasons. I know there is a linux build, I know there is worse performance on VM. Sometimes I want to test something without touching my main system and without switching to Windows. VM is great for this.

**Comment by wheremyfoodat** [comment]
@hercc82 If you specifically want to use the Windows version on your Linux machine, have you considered running the executable through a compatibility layer like `wine`? That should be both faster, more lightweight and less of a hassle than VirtualBox. If you specifically want a VM then your best bet would be to fiddle with the VirtualBox display settings or use a less outdated solution like VMWare.

**Comment by nicolasnoble** [comment]
I don't have VirtualBox myself, and this is an error deep within glfw, really. It could be more of a glfw issue than a pcsx-redux one at the end of the day. Some Googling seems to indicate that glfw and virtualbox aren't necessarily the best of friends.

**Comment by hercc82** [comment]
An interesting and quite recent topic https://forums.virtualbox.org/viewtopic.php?f=2&t=101304

It seems VirtualBox supports only OpenGL 2.x but your application requires OpenGL 3+. There is some workaround like Mesa3D  however, it is not an ideal solution. So Windows on VirtualBox and pcsx-reduc cannot cooperate at this time. 

I think that's it for this topic.

**Comment by nicolasnoble** [comment]
Depending on what "touching your main system" means, but there is a fully self-contained AppImage binary build for Linux that's available.

**Comment by lorn10** [comment]
Just for "reference", I thought really that I was somewhat crazy to run the PCSX Redux Windows binaries under Wine (on Linux). But this here now shows in some way that this matter can get even crazier.... ;-)

@hercc82 Maybe an older **PCSX Reloaded** build will run in VirtualBox. So far I understand most (or some?) of them are OpenGL 2.x based.

And regarding Linux PSX gaming, - I can confirm that the PCSX Redux Linux AppImage binaries are in the overall handling fully comparable to a Windows binary. :+1: 

Whatever, maybe I should now really try out how the famous notorious **N64 UltraHLE emulator** runs on latest Wine releases. Maybe it works (with the correct Glide to OpenGL wrapper) better then some 20 years ago under Windows Me (Windows Millennium Edition). :-P
