### ISSUE TITLE
Controller loses its function

### ISSUE THREAD

**Issue by hercc82** [grumpycoders/pcsx-redux#527]
System:
Windows 10, up to date
GTX 960
pcsx-redux 4470.20210615.8.x64
pcsx-redux uses default settings except FPS limit was activated
Original PSX Controller is connected through USB Adapter
Tested only with Crash Bandicoot 

At first, I have to say the PSX Controller detection was good. I didn't have to configure its button manually. I could just start playing with the controller connected. 

Issue:
The left analog loses some its functions after a while. For example I need to push the analog 3-4 times to move right or moving diagonally (right and down) stops working completely. 

For the first time the problem occurred after 1-3 minutes of play. Later I was able to play 5-15 minutes and the problem occurred again. I currently have a save where the problem occurs as soon as it is loaded. This makes the game unplayable with this controller using analog.

In the meantime I was playing on psxc2 and could not observe such problem so I rather don't suspect a problem in the controller hardware.

**Comment by hercc82** [comment]
I tried Mednafen and I was not able to run analog/dualshock with Crash Bandicoot on Mednafen. 

Interesting topic about ePSXe and Crash Bandicoot https://www.reddit.com/r/emulation/comments/2l22dh/epsxe_analog_sticks_not_working_in_crash_bandicoot/

>Crash bandicoot doesn't have support for the dualshock 1. It came out before that pad existed so no analogue controls.

According to Wikipedia Crash Bandicoot was released on 
    NA: September 9, 1996
    EU: November 8, 1996 
but DualShock/Analog was introduced in November 1997.

I am interested to see how the games behaves with DualShock on a real PlayStation. I currently do not have a console, but this will change. If anyone currently has a console and the game on hand I would love to know how the game behaves then with DualShock.

**Comment by wheremyfoodat** [comment]
>  I currently have a save where the problem occurs as soon as it is loaded
Does this issue always arise at a specific part of Crash Bandicoot?
It would be nice to get some feedback on if it works properly on other games, to narrow down whether it's a pad handling problem or if it could possibly be an emulation issue (mostly leaning on the former, knowing how... finicky controllers get)

**Comment by hercc82** [comment]
@wheremyfoodat 

>Does this issue always arise at a specific part of Crash Bandicoot?

It is difficult to say for me. In case of my save I could reproduce it immediately after loading this save. In other cases hard to say. I will for sure play another games like Crash Bandicoot 2 and 3 with pcsx-redux and report my feedback. However, it may take some time because my time is limited. However, the information that the game does not work with analog makes me optimistic, because it's possible that it's the fault of the game itself, as I wrote above. For me, it would be interesting to know about the real psx console and Crash Bandicoot. Maybe I can verify it soon.

**Comment by wheremyfoodat** [comment]
Thanks for dedicating the time for this ❤️

**Comment by hercc82** [comment]
I played Crash Bandicoot recently on PSX. I can say now for sure CB doesn't work with analog. When analog controller connected and analog is turned on then the whole controller stops working. It is possible to control when analog is disabled only. In the future I will try CB2 and CB3 on pcsx-redux. If everything is ok there, it will mean that the controller handling in CB/pcsx-redux is not perfect. Then it would be better to either add properly working dualshock in CB and give more options than on real PSX or disable the option completely like mednafen.

**Comment by lorn10** [comment]
Sorry to warm up this post but I can confirm that **Crash Bandicoot 1** (Platinum Edition) is working great with the analog controller of the **8BitDo Pro 2** gamepad. :+1: 

So it looks that only the very original Crash Bandicoot release hadn't any support for the analog sticks while the later Platinum Edition had it. So this is not a bug of PCSX-Redux, this is most likely a limitation of the very first Crash Bandicoot game release.

Out of my view this issue can be closed @wheremyfoodat .

@hercc82 Some more information about the really nice 8BitDo Pro 2 BT & USB-C gamepad can be found here: https://github.com/grumpycoders/pcsx-redux/issues/382#issuecomment-854070189
But it is not PSX compatible, only PC (Linux, Mac OS, Windows) and Nintendo (switch).

Game data: Crash Bandicoot, Platinum Edition, CD-label **SCES-00344**
![Startmenue_Crash_Bandicoot_1](https://user-images.githubusercontent.com/9931771/127205230-0bdc9b06-8267-4598-a9d7-29927827b74a.png)

**Comment by hercc82** [comment]
@lorn10 @wheremyfoodat 

>Sorry to warm up this post but I can confirm that Crash Bandicoot 1 (Platinum Edition) is working great with the analog controller of the 8BitDo Pro 2 gamepad.

Did you play at least 15 minutes? 

>So it looks that only the very original Crash Bandicoot release hadn't any support for the analog sticks while the later Platinum Edition had it.

I don't agree. I am almost certain but not 100 % sure that the version I tested on the original Playstation One was Crash Bandicoot Platinum (for Europe). I don't know which version I played on pcsx-redux but I will check both soon. 

Did you test the platinum version on the original console and can you confirm analog sticks work? If not I would hold off on saying that this game ever supported analogue at all. The original game was released before analogue existed, so it couldn't support it. The question is when was the platinum version released and how do they differ at all?

For me the bug still exists but the topic requires much more input.

**Comment by lorn10** [comment]
@hercc82 
I play **Crash Bandicoot 1** (Platinum Edition) SCES-00344 (the **PAL** version) with my **8BitDo Pro 2** gamepad in PCSX-Redux and the analog controller works **perfectly well**. That is what I can confirm. But I didn't test the game at real PS1 hardware, only in newer PCSX-Redux builds.

This is my awesome **8BitDo Pro 2** gamepad which is at the technical level of a PS4 controller:
![8BitDo_Pro_2](https://user-images.githubusercontent.com/9931771/131477171-2abc1763-659e-44f9-87c3-f07934e9b421.png)
![8BitDo_Pro_2_Input_switch](https://user-images.githubusercontent.com/9931771/131477199-7aa1bf68-e446-42e8-b283-07a75d237f17.jpg)
