### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by P0W3** [grumpycoders/pcsx-redux#534]
In pcsx-redux-nightly-4530.20210713.2-x64, I kept pushing the config button for Square, and it is not happening.

![image](https://user-images.githubusercontent.com/18279115/126261706-d6dc8a4f-0056-4305-baa5-49d90b998c3d.png)
![image](https://user-images.githubusercontent.com/18279115/126261864-01863130-27c2-4278-80b9-279c14760cd4.png)

Actually, never mind. I discovered something out.

**Comment by wheremyfoodat** [comment]
@P0W3 Hello!
Thanks for taking the time to find and report this issue. It should now be fixed by PR #536
