### ISSUE TITLE
Add the Shortcut Keys in PCSX-Redux

### ISSUE THREAD

**Issue by P0W3** [grumpycoders/pcsx-redux#535]
I am very interested to have the shortcut keys in PCSX-Redux.

A few examples should be these. The Pause key to pause the emulator or the F12 key to take a picture.

**Comment by lorn10** [comment]
Just for reference, there is a merge request underway which will implement some basic support for shortcut keys: https://github.com/grumpycoders/pcsx-redux/pull/542 :+1:

**Comment by wheremyfoodat** [comment]
Yeah, that PR was made in response to this issue but I forgot to mention it.

**Comment by nicolasnoble** [comment]
@wheremyfoodat you still waiting on something to merge it by the way?

**Comment by lorn10** [comment]
@wheremyfoodat That's funny, - even I as a "non-def" have asked me why the merging of #542 takes so long...
The next time I will send you a "merge-reminder". :-P Whatever, I and most likely also the OP are happy that this really useful function is soon avaiable in PCSX-Redux! ;-)
