### ISSUE TITLE
JIT (Dynarec) support for arm and aarch64

### ISSUE THREAD

**Issue by Ntemis** [grumpycoders/pcsx-redux#544]
Greetings,
Any chance this gets done this year?
I would very much like to start using this emulator in batocera and upcoming retrolx distibutions.
Regards from Cyprus

**Comment by wheremyfoodat** [comment]
@Ntemis
Hello! There's currently no concrete plans for when Redux will get an AA64 dynarec, as there's currently other priorities and most contributors don't have any ARM devices (discounting phones) readily available. However there's still a possibility it will happen eventually, and contributions are always welcome.

**Comment by wheremyfoodat** [comment]
Reopening for visibility because even if it's not planned for the very near future, it's a feature that would be pretty nice to have (albeit a pretty large undertaking).

**Comment by wheremyfoodat** [comment]
Alright, this might get bumped a bit in my TODO list for the future now.

**Comment by wheremyfoodat** [comment]
There's now arm64 recompiler support for Linux and MacOS. It's still pretty in a pretty early state, so some bugs are expected, but it works for a decent amount of games.

**Comment by nicolasnoble** [comment]
So this one's completed, really. We haven't heard of complains about it, so we should consider it working. If there's specific issues using the aarch64 recompiler, they should be done using separate issues.
