### ISSUE TITLE
Add CHD Support

### ISSUE THREAD

**Issue by ducalex** [grumpycoders/pcsx-redux#546]
CHD is a compressed image format that is supported by MAME, Redream, DuckStation, most cdrom-based RetroArch cores, etc. I have [added support for it](https://github.com/ducalex/pcsx-redux/commits/chd-support) using code from [another pcsx fork](https://github.com/libretro/pcsx_rearmed) but I have questions before submitting a pull request for your consideration.

- The code depends on [libchdr](https://github.com/rtissera/libchdr/) which bundles lzma and zlib. Should I add libchdr and lzma to the tree or should it be a remote submodule?
- Where and how should I add a reference to pcsx-rearmed (or the author of the code)?

Thanks

**Comment by nicolasnoble** [comment]
You're more than welcome to make pull requests, yes :-)

The general code style we're using is that most things ought to build out of the box when checking out the repository on development machines. It's acceptable if on Linux and MacOS there's packages being required, as long as they are readily available on common package distributions. On Windows, either nugget packages should be used, or things should compile cleanly from the third_party submodules.

In short, here's sort of the decision tree when adding a new dependency:

- If a nugget package exists, use it on Windows.
- If a commonly, easily installable (apt-get install) Linux package exists use it on Linux.
- If a brew package exists on MacOS, use it on MacOS.
   --> If any of these 3 pre-conditions aren't validated, have a submodule and build from source for the missing cases, using the Makefile at the root, or using a visual studio project file.

I can point to more specific parts of the repository to show more details if required.

With regards to credits and references, I've tried to work it all out in the [AUTHORS](https://github.com/grumpycoders/pcsx-redux/blob/main/AUTHORS) file at the root of the repository, that's shipped with the rest of the codebase. I haven't made it part of the "About" menu yet, but I should.

**Comment by ducalex** [comment]
Perfect, I should be able to figure out the Makefile and VS project changes needed and make sure that it builds cleanly on Windows and Linux but I won't be able to test on MacOS X.

I also see that you are using clang-format so I will make sure it is happy with my changes :).

**Comment by nicolasnoble** [comment]
I don't have MacOS either, I just let the ci yell at me if something breaks. There's a script in the .github folder that installs all the brew dependencies, which hopefully should be enough here.

For the code format, there's a github bot that issues pull requests automatically to fix the style, so it's not a big deal.

**Comment by lorn10** [comment]
@ducalex Just out of curiosity, how can I make such compressed CHD files under Linux? 

At the moment I use for my PSX games a handy and convenient GUI tool called **AcetoneISO**. It has a special "**Playstation 1 Game**" option which generates a ".bin file. (I rename that extension then to *.**psx**, like "Crash_Bandicoot_SCES-00344.psx"). This works great in PCSX-Redux, but it would be nice if the storage space consumption could be reduced.
![AcetoneISOpsxImage](https://user-images.githubusercontent.com/9931771/127829839-fe4f7b6b-cd53-4e64-abd4-30482f56ae0e.png)

**Comment by ducalex** [comment]
@lorn10 The official (and only?) tool is the command-line utility chdman from MAME. There's a [short guide here on basic usage](https://retropie.org.uk/docs/CHD-files/). It will work on the raw image created by Acetone but I don't know if it can rip a /dev/cdrom directly.

It might take a while to get CHD merged in so, if you want, pcsx-redux already supports a few compressed formats:
- PBP: This is a PSP PS1 format
- CBIN: (Which is CSO/CISO)

Tools for both are mentioned on this page:
https://emulation.gametechwiki.com/index.php/Save_Disk_Space_for_ISOs

**Comment by nicolasnoble** [comment]
So, I checked a bit, and unless I am missing some details, the chd format is destructive in the sense that it isn't storing the index information from the original disk. This means the TOC cannot be accurately reconstituted from the chd files after conversion, and the pregap locations will be missing. This will create inaccuracies in some games that rely on pregaps that aren't actually 2-seconds wide.

I've been busy trying to cleanup the cd image parsing code, and I spent a lot of time making sure the TOC is being reconstituted accurately. I don't think adding a file format that's going to break some games and potentially make users file bugs related to emulation accuracy is a good idea. This is basically a footgun, and shouldn't be used.

**Comment by drpetersonfernandes** [comment]
Check ou [https://github.com/drpetersonfernandes/SimpleLauncher](https://github.com/drpetersonfernandes/SimpleLauncher)

This emulator frontend can mount the CHD file using a virtual drive (requires Dokan). It creates a virtual cue/bin of the chd on the virtual drive. Then automatic launch the game into pcsx-redux.
Check it out.
