### ISSUE TITLE
Regression in recent Linux build, error: GLSL 4.10

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#588]
Hi all

It looks that the newest Linux build a0a9478b is affected by an annoying little bug:
```
test@test-iMac:~$ $HOME/Downloads/PCSX-Redux/Linux/./PCSX-Redux-HEAD-x86_64.AppImage
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader! With GLSL: #version 410

0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader! With GLSL: #version 410

0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! With GLSL #version 410

error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```
So this means effectively that all **OpenGL 3.x** hardware is currently blocked. Maybe this is true also for the Windows build?

However, in my special case, because I have a DX11 compliant GPU which is "wrongly" advertised as just OpenGL 3.3, I can do `MESA_GL_VERSION_OVERRIDE=4.3 MESA_GLSL_VERSION_OVERRIDE=430` in `/etc/environment` and PCSX-Redux is happy again. :+1: 

Of course, this doesn't work with my Intel HD 2000 "Sandy Bridge" iGPU which is effectively just OpenGL 3.3 compliant.

**Comment by nicolasnoble** [comment]
This was to alleviate https://github.com/ocornut/imgui/issues/4463 which is now fixed upstream, so this can be reverted while pulling a new version of imgui.

Thanks for the heads up, I wasn't sure if this would affect people.

**Comment by nicolasnoble** [comment]
Correction: this isn't in the imgui docking branch yet. We'll have to wait a bit until @ocornut does a master-to-docking merge, which happens usually fairly frequently.

**Comment by ocornut** [comment]
(updated `docking` now)
