### ISSUE TITLE
SCES-02105 CTR: Crash Team Racing

### ISSUE THREAD

**Issue by Ryusan-AT** [grumpycoders/pcsx-redux#68]
http://redump.org/disc/897/

- Bios Sony - Carte Nvidia GTX 880M

Le jeu bloque à l'écran 'Sony Computer Presents', même avec le fichier SBI.
Bloque également sur la version patchée.

**Comment by wheremyfoodat** [comment]
Fixed with the addition of Capture Buffer IRQs (enabled by default as of #689). Game is now playable provided you don't turn that option off (Option might be removed and be permanently enabled in the future).
