### ISSUE TITLE
[Linux] PSX OpenBIOS issues with new 64bit Dynarec

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#695]
Hi all!

Here follows an issue which I can confirm for recent **Linux builds** (like 6d4409ab). This is definitively Linux-only related because it doesn't happens with the Windows builds (like 6573) under Wine/Linux. I described this the first time in bug #656 when the new 64bit dynarec was introduced in PCSX-Redux.

In short, the main relevant symptom is that I get **heavy screen corruptions** in **Crash Bandicoot 1** when the new Dynarec is used in conjunction with the PSX OpenBIOS. Furthermore **Crash Bandicoot Warped** is **not even launchable / playable**, it crashes right after the OpenBIOS is loaded with an "[Unrecoverable error while running recompiler](https://github.com/grumpycoders/pcsx-redux/issues/656#issuecomment-986268524)".

![Crash_Bandicoot_PCSX-Redux_build6d4409ab](https://user-images.githubusercontent.com/9931771/147404702-d41c2c7d-50a9-492c-a227-d0305609c338.png)
![Crash_Bandicoot_PCSX-Redux_build6d4409ab_2](https://user-images.githubusercontent.com/9931771/147404712-365d9f79-3496-47eb-945e-677af4c66ee5.png)

Interestingly the situation looks totally different when an original PSX BIOS, like in my case **SCPH-7502 BIOS v4.1**, is used. Everything works almost perfectly. However, this is also true when the normal Interpreter is used with the PSX OpenBIOS. So this error occurs on Linux only in conjunction with the PSX OpenBIOS and the new 64bit Dynarec not with the 64bit Interpreter.

![Crash_Bandicoot_PCSX-Redux_build6d4409ab_Dynarec stockBIOS](https://user-images.githubusercontent.com/9931771/147405522-ab07b6c9-7447-435c-bf2d-2578a0ebe9ab.png)
![Crash_Bandicoot_PCSX-Redux_build6d4409ab_Interpreted](https://user-images.githubusercontent.com/9931771/147404748-82ab6841-f84a-400b-a06f-737f09855180.png)

Finally I say all involved many thanks for their GREAT effort and work in this matter! I wish all leisurely remaining holidays. :+1:

**Comment by wheremyfoodat** [comment]
Yeah, OpenBIOS does do all sorts of cursed things that might throw off the dynarec. If you really want to laugh your heart out, try using OpenBIOS + dynarec with the original Spyro The Dragon.

Will look into it once I get the chance @lorn10

**Comment by wheremyfoodat** [comment]
Could you please try again with the latest build when it's uploaded? Latest build also fixes the graphics bugs in your fave games (Like CB: Warped)

**Comment by lorn10** [comment]
Sorry for the late answer. Okay, I am now on build dd5ff077 and the issues are still there for both mentioned games.

So when the new 64bit dynarec is selected then I get with **Crash Bandicoot Warped**:

![Crash_Bandicoot_PCSX-Redux_builddd5ff077](https://user-images.githubusercontent.com/9931771/156937622-0019a044-bd64-46d6-b33c-8665da38eda1.png)

**Note**, because the Linux PCSX-R package doesn't includes a PSX OpenBIOS file, I chose always that one from the Windows build which is currently **7587**: `/home/test/Downloads/PCSX-Redux/openbios.bin`

I hope this isn't a problem?

**Comment by lorn10** [comment]
A status update, all problems described here seems to be resolved in more recent PCSX builds like **8898**. Everything is rendered and working correctly and I see no difference between the PSX OpenBIOS and regular stock BIOS. :+1: 

Only downside is that all my save-states and memory-card saves no longer work. They are simply no longer recognized. Is that technically related, so because of a change in the "saving design"? @wheremyfoodat 

Note, this is true for the Windows build under Wine/Linux. I cannot test currently the native Linux build because the Linux CI is broken sine end of April.

Whatever, really GREAT work devs! It looks that PCSX-Redux makes this year **impressive progress**. Maybe it is time for a first **v0.1 build** when the OpenGL stuff lands. :smile:

**Comment by wheremyfoodat** [comment]
@lorn10 Savestates haven't gone through any significant changes in a while. #788 would break those normally but it hasn't been merged yet. Memory cards that were made with OpenBIOS + the x64 dynarec before some fixes were made might be corrupt on the other hand, causing them not to be recognized.

Is there any error message shown or anything? Maybe your cards/states are in the wrong directory?

**Comment by lorn10** [comment]
There is no explicit error message. The memory-card is just detected as total empty. And the save states are not loaded (they are located in the PCSX-Redux folder were the exe file is).

However, my save-states (and also the memory-card files) were made by the **Linux build**. So there could be also an incompatibility between the Linux and Windows build? But at least the memory-card saves should be compliant between the OS specific PCSX-Redux versions.

Will retest this with the native Linux build when the **Linux CI** is fixed. :+1:

**Comment by lorn10** [comment]
Okay, for whatever reason it works now. And I have no idea why. :wink: 

Maybe because I switched at the CLI to the PCSX-Redux `Linux` folder. And when I start after that the Windows build from the CLI then it will take the `pcsx.json` configuration file from the Linux build.

So I can start the Windows build with the config of the Linux build and then all the saves and save-states are present. Nice to know...

**Comment by wheremyfoodat** [comment]
Yeah. The savestates, memory cards and config file should work across all platforms.

**Comment by lorn10** [comment]
A final addition to this topic. I can now explain what happened. In short, - the Windows build has now the behavior of the Linux build when running under Wine.

So when I launch the console, I am always in the **user folder** which is in my case `/home/test/`. And this is then also the location were the config files of PCSX-Redux lands when it is launched directly from CLI via `WINEPREFIX=~/.wine wine /home/test/Downloads/PCSX-Redux/pcsx-redux.exe`.

I think this was not true in the past. Windows applications usually chose the directory of the exe file as their working directory. This is true for example in conjunction with CXBX-R, the Xbox "emulator". When I launch it with `WINEPREFIX=~/.wine wine /home/test/Downloads/Cxbx/cxbx.exe` then it will take `/home/test/Downloads/Cxbx/` as working directory. So it has no effect from were I launch the exe file, even when I am in `/home/test/` the config file will land in `/home/test/Downloads/Cxbx`

This is no longer true for the Windows build of PCSX-Redux which acts now in the same way as the Linux build. Anyway, I've learned again quite somewhat. :+1:
