### ISSUE TITLE
fmt not found running dockermake

### ISSUE THREAD

**Issue by nojhan** [grumpycoders/pcsx-redux#697]
While running `./dockermake.sh` at 337afd6e0f481936dcfab4af56fe444510113b1b on Ubuntu 20.04, the following error is repeated several times, ending the build:
```
src/core/system.h:33:10: fatal error: 'fmt/printf.h' file not found
#include "fmt/printf.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** wait: No child processes.  Stop.
```

**Comment by wheremyfoodat** [comment]
@nojhan Are you sure you cloned the repository properly, with submodules?
Can you share the contents of your third_party directory?

**Comment by nojhan** [comment]
That was the case, sorry for the noise. Made PR #701 to help avoid further noise.
