### ISSUE TITLE
Memory card not working on OpenBIOS

### ISSUE THREAD

**Issue by glitch-in-the-herring** [grumpycoders/pcsx-redux#709]
### Describe the bug

When trying to open a save file from the main menu of Breath of Fire III/IV, the game raises an error because the memory card is not found/not inserted. When writing save files, the game thinks that the memory card is unformatted. 

### Expected behavior

The game should read and write the memory card properly with no error messages.

### Steps to reproduce the bug

1. Change the BIOS to OpenBIOS
2. Move the attached memory card to PCSX-Redux's folder, and rename it to memcard1.mcd so that it's the first memory card
3. Open Breath of Fire III (SLES-01304)
4. Press start. An error should appear saying that no memory card was inserted

### Operating System

Windows 10 Build 19043

### CPU model

AMD Ryzen 5 4600H

### GPU model

Nvidia GeForce GTX 1650 Ti

### BIOS version

OpenBIOS

### CPU emulation mode

Recompiler

### Additional information

Tested with:
*SLES-01304 Breath of Fire III (PAL, English)
*SLUS-01324 Breath of Fire IV (NTSC)

Memory card: [bofiii main.zip](https://github.com/grumpycoders/pcsx-redux/files/7814926/bofiii.main.zip) (SLES-01304)

This does not occur when using the SCPH-7001 BIOS

**Comment by wheremyfoodat** [comment]
Probably an issue with load delay slots in the recompiler. Should probably try using the interpreter with OpenBIOS until it's fixed.

**Comment by wheremyfoodat** [comment]
![image](https://user-images.githubusercontent.com/44909372/156434488-c03fd2d2-84df-4bb8-aa35-37e64635aa25.png)
Fixed in #744, should be merged soon
