### ISSUE TITLE
Fromage (Homebrew) still does nothing work?

### ISSUE THREAD

**Issue by qamichele594-2** [grumpycoders/pcsx-redux#717]
### Describe the bug

Nothing but CRASH.

### Expected behavior

No response.

### Steps to reproduce the bug

No response.

### Operating System

No response.

### CPU model

No response.

### GPU model

No response.

### BIOS version

No response.

### CPU emulation mode

Recompiler

### Additional information

No response.

**Comment by nicolasnoble** [comment]
Yeah, that's not a useful report at all.
