### ISSUE TITLE
Memory Card Manager: changes are not applied

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#719]
### Describe the bug

@wheremyfoodat Thanks for this GREAT new addition! :+1:  :smile: 

So I have tested a little bit the new **Memory Card Manager** in PCSX-Redux build 1df1dddd.

Unfortunately it seems that for me all changes which I make are not effectively saved to the memory card. So when I `format`, `copy`, `move` or `swap` one or more blocks then this change is simply not applied. All changes are lost when PCSX-Redux is restarted.

I can confirm this behavior for PSX OpenBIOS and also the original stock BIOS. This is as well present under Linux as also under Wine with the Windows build (6798).

@wheremyfoodat 
Maybe it would make sense to change the current behavior when a save block is swapped with its own (the same) number. At the moment it looks the save block data will be destroyed when I swap for example block 5 with 5. (Yes, this action makes really no sense but sometimes this can occur if one is too careless.) Whatever, the most logical action would be that simply **no change** is made to the corresponding save block in this situation.

### Expected behavior

All the changes processed in the new Memory Card Manager should get applied.

### Steps to reproduce the bug

1. Go to "Memory Card Manager"
2. Make a change to some save blocks
3. Reboot PCSX-Redux and you will see no change is applied

### Operating System

Kubuntu 20.04 LTS

### CPU model

Intel Core i5-2500S

### GPU model

AMD Radeon HD 6770M

### BIOS version

both are affected

### CPU emulation mode

Interpreter

### Additional information

In the attachement follows my Crash Bandicoot related `memcard1.mcd` file.
[memcard1.mcd.zip](https://github.com/grumpycoders/pcsx-redux/files/7986398/memcard1.mcd.zip)

And a picture:
![Crash_Bandicoot_PCSX-Redux_build1df1dddd_MCM](https://user-images.githubusercontent.com/9931771/152154952-e3994213-d6af-4194-9fd6-8cac6e381973.png)

**Comment by wheremyfoodat** [comment]
Remember to press the "Save card to file" option after you're done. If you do that and reboot then you should see your changes.

**Comment by wheremyfoodat** [comment]
Gonna look at the "swap block with itself" thing later tonight, it *should* do nothing unless you eg swap block 5 of memcard 1 with block 5 of memcard 2

**Comment by lorn10** [comment]
:rofl: Thanks for the hint! :rofl: How embarrassing! It was really just that "Save card to file" action which I didn't realize what it means. 
(For me this looked something like an "export to a file" function or so.)

I really assumed that the save block changes would take **immediate** effect so in **real time**. (I think this is the normal behavior in PCSX-Redux, - at least regarding the "Configuration" section. It's nowhere necessary to save the changes separately.)

Maybe it would make sense to call it just "**Save**" button? In regard to the "simple minded people", and because sometime "less" could be really "more". But we ask better Nicolas Noble about his view of that....

I should mention that I am not native English so this could also explain somehow my misunderstanding of this wording. And maybe I am also simply too old for this stuff here. :wink: 

Whatever, I am closing this, - the problem effectively never existed. It was just a misinterpretation by myself. Thanks again! :+1:

**Comment by wheremyfoodat** [comment]
No worries. @nicolasnoble does agree it should be changed, so we'll try to get it fixed asap.

As for the "swapping block with itself" issue, it works as expected for me
