### ISSUE TITLE
Copying logs copies content from other windows as well

### ISSUE THREAD

**Issue by glitch-in-the-herring** [grumpycoders/pcsx-redux#721]
### Describe the bug

When pressing the `copy` button on the logging window, the contents of another window, such as the memory editor, or the assembly window, will be copied along. This happens when the logging window is docked with another window.

### Expected behavior

Only the logs should be copied

### Steps to reproduce the bug

![Screenshot 2022-02-03 183256](https://user-images.githubusercontent.com/70984234/152335277-e0f70034-7b08-4b39-b2c3-501b254b2dc9.jpg)
1. Open PCSX-Redux
2. Open the logging window
3. Have the logging window be docked with another window (like shown in the screenshot above)
4. Open a memory editor
5. Press `copy` on the logging window
6. Paste the copied text
7. 
![Screenshot 2022-02-03 183631](https://user-images.githubusercontent.com/70984234/152335654-18be79ef-2825-4e33-a416-50d5f9bf4106.jpg)

### Operating System

Windows 10 Build 19043

### CPU model

AMD Ryzen 5 4600H

### GPU model

Nvidia GeForce GTX 1650 Ti

### BIOS version

OpenBIOS

### CPU emulation mode

Interpreter

### Additional information

None

**Comment by wheremyfoodat** [comment]
A build with this bug fixed should be up any time now.
