### ISSUE TITLE
cannot use second controller

### ISSUE THREAD

**Issue by mnagel** [grumpycoders/pcsx-redux#743]
### Describe the bug

I have two XBox controllers, both of them working with PCSX-Redux (one at a time), both of them working at the same time with other applications. I noticed that by default pad 2 is not connected (in the Configuration->Controls menu).

Setting the checkbox for "connected" does not change anything, still only one controller. Disabling pad1 and enbabling pad 2 will give me one working controller again, but I cannot find a way to make them both working.

### Expected behavior

Both controllers should be working with no or minimal, obvious configuration.

### Steps to reproduce the bug

1. Connect two controllers to your PC
2. "Connect" both pads in Configuration->Controls menu
3. Start emulation
4. Expect two controllers, see that only one controller is active

### Operating System

Windows 10

### CPU model

Ryzen 7

### GPU model

GTX 1060

### BIOS version

unsure, OpenBIOS probably

### CPU emulation mode

Recompiler

### Additional information

n/a

**Comment by mnagel** [comment]
I just saw 39326de506a61f6a6429cd3e888a6ed247c100a1 so this seems to be an active topic.
So probably relevant to mention that I used pcsx-redux-nightly-7209.20220219.17-x64

**Comment by wheremyfoodat** [comment]
What if you set "Connected" to true for both, then press the rescan gamepad button?

**Comment by mnagel** [comment]
Tried that, did not change anything. I will also attach a screenshot of the dialog in question so you can maybe spot any misconception on my side. There are two entries in the "Gamepad" dropdown on the bottom, but not choice down there for either controller changes anything.

![grafik](https://user-images.githubusercontent.com/961159/155196905-f6b3e7df-648f-4393-b089-e2302bb345a1.png)

**Comment by nicolasnoble** [comment]
Got myself a second controller and I've found the reason for this one :P
