### ISSUE TITLE
Memory card 2 not usable and / or not properly detected

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#748]
### Describe the bug

Hi all!

I am on PCSX-Redux Linux build 0ac61978 and it looks that the memory card 2 is completely unusable. This is true for **Crash Bandicoot Warped** and also **Crash Bandicoot** with the PSX OpenBIOS and the stock retail one.

The output is simply "An error has occurred":
![Crash_Bandicoot_Warped_PCSX-Redux_build0ac61978](https://user-images.githubusercontent.com/9931771/155837232-dff334d7-aba9-44e2-a968-76150fcd66cd.png)

It should be noted that the memory card 2 never worked for me properly. So I never saved anything direct to it but I have used the new memory card manager to copy some data from mc1 to mc2. However, the content is because of the bug not recognized.

For more information see the memory card files in the attachment. :+1: 
[mc1&2_26022022.tar.gz](https://github.com/grumpycoders/pcsx-redux/files/8146280/mc1.2_26022022.tar.gz)

### Expected behavior

The memory card 2 should be usable as card 1.

### Steps to reproduce the bug

Please use the attached mc files to reproduce the problem.

### Operating System

Kubuntu 20.04 LTS

### CPU model

Intel Core i5-2500S

### GPU model

AMD Radeon HD 6770M

### BIOS version

both are affected

### CPU emulation mode

Interpreter

### Additional information

The problem is also present with the Windows build under Wine.

**Comment by wheremyfoodat** [comment]
I will be checking this when I'm on PC later tonight, but just to make sure, is the "Memory card 2 inserted" checkbox in the memory card manager checked?

**Comment by lorn10** [comment]
@wheremyfoodat Yes, the checkbox is set. :wink: 

And mc 2 is even not detected when I uncheck mc 1.

**Comment by wheremyfoodat** [comment]
@lorn10 I'll try to see if I can find anything soon then

**Comment by lorn10** [comment]
Interesting, then this is a Linux related issue? As mentioned, the saving on mc 2 is in my case simply not recognized when I want to select a save state in the game **Crash Bandicoot Warped** via the normal "Load" function. The above message is right after this displayed.

Furthermore when I uncheck mc 1 it is also not possible to make a new fresh saving to mc 2. Will delete both mc files and check the behavior with empty ones. So will report back later. :+1:

**Comment by lorn10** [comment]
A short update, this issue still exists for me also with PCSX-Redux build e37d9a56.

And regarding the original **Crash Bandicoot** game there is a (strange) difference between the number of loading states.

With PSX OpenBIOS (from the Windows build 8340) I have at the position 11 a **damaged slot**:
![Crash_Bandicoot_PCSX-Redux_builde37d9a56_PSXOpenBIOS](https://user-images.githubusercontent.com/9931771/161436908-3857a071-9fe7-4519-80ec-6e7dc498e2ae.png)


While with the stock retail BIOS SCPH-7502 BIOS v4.1 this is not the case, slot 11 is empty (which is correct):
![Crash_Bandicoot_PCSX-Redux_builde37d9a56_RetailBIOS](https://user-images.githubusercontent.com/9931771/161436835-184b9cc0-901c-42dc-a821-53cf8ba95a2f.png)

And finally, it would be really helpful for Linux users to know which PSX OpenBIOS file is effectively the "best one". I use the `openbios.bin` file because it has the same size as the original bios. But maybe I should use on Linux the variant with elf extension, so `openbios.elf`. This also works but is has the same issue. Whatever, any hint which bios file should be when used would be quite helpful, thanks @wheremyfoodat. :+1:

**Comment by wheremyfoodat** [comment]
OpenBIOS does still have some memory card woes in a lot of games, we discovered that a few weeks ago. So yeah, not as stable as the retail BIOS for a decent amount of games. You should use the bin file btw, regardless of OS

**Comment by wheremyfoodat** [comment]
Also I'm not sure, but you might want to make a new memory card. Your current one might be corrupted.

**Comment by johnbaumann** [comment]
Hello there. There's been some updates to the memory card code in both redux(via #995) and openbios(via #1004) . I did some brief testing of the games mentioned and they appear to work. Could you please confirm if you are still having issues @lorn10 @glitch-in-the-herring ?

**Comment by glitch-in-the-herring** [comment]
I can confirm that the issues don't appear anymore.

**Comment by lorn10** [comment]
A short status update. There is a change in the topic. Instead of the mentioned error message (see first picture) I have now an other message which tells me to insert a memory card into slot 1. This occurs always and regardless of whether the memory card 2 is empty or contains some data (which is copied over from card 1).

![PCSX-Redux-72dbece7-linux-x86_64](https://user-images.githubusercontent.com/9931771/202516298-8536bb19-3a51-4120-b28d-0f107c9ad244.png)

So it looks that the underlying problem is not resolved for me. The memory card 2 is not usable, it is simply not detected. Maybe this is a Linux specific issue. I am now on **Kubuntu 22.04 LTS**.

**Comment by wheremyfoodat** [comment]
AFK at the moment so I can't test for myself, but might be worth trying the game with a fresh, blank memory card. Dynarec/OpenBIOS bugs have led to the creation of corrupt memory card images in the past with all sorts of funny problems.

**Comment by johnbaumann** [comment]
> A short status update. There is a change in the topic. Instead of the mentioned error message (see first picture) I have now an other message which tells me to insert a memory card into slot 1. This occurs always and regardless of whether the memory card 2 is empty or contains some data (which is copied over from card 1).
> 
> ![PCSX-Redux-72dbece7-linux-x86_64](https://user-images.githubusercontent.com/9931771/202516298-8536bb19-3a51-4120-b28d-0f107c9ad244.png)
> 
> So it looks that the underlying problem is not resolved for me. The memory card 2 is not usable, it is simply not detected. Maybe this is a Linux specific issue. I am now on **Kubuntu 22.04 LTS**.
> 
> **Addition**: This happens with stock and latest PSX OpenBIOS. Tested build was PCSX Redux build [72dbece](https://github.com/grumpycoders/pcsx-redux/commit/72dbece7351f0f9fb361f3a2617714fe33928973).

Is there a particular way to access memory card 2? I've tested with a few emulators and haven't seen any mention of card 2.

**Comment by lorn10** [comment]
Okay, so you mean that the game itself doesn't support more than one memory card? 

Maybe this is really the point, - I haven't found an option _in the game_ were you can chose the memory card. I assumed that all PSX games are supporting at least two memory cards. (I think this is/was the situation at the N64 console.)

So in the end this here will be then not a bug in PCSX-Redux (or PSX OpenBIOS) but rather a limitation of the corresponding PSX game. This would mean that Crash Bandicoot and Crash Bandicoot Warped only supports exactly _one_ memory card which has to be **memory card 1**.

**Comment by johnbaumann** [comment]
I believe this to be the case, yes. This was not uncommon for titles of the era/platform, especially in one-player games.

**Comment by lorn10** [comment]
Okay then I will close this issue report. 

But it would be somehow really nice to have an in-built function in PCSX-Redux which would automatically expose **memory card 2** as **memory card 1** when the _effective_ memory card 1 is disabled / unchecked. @wheremyfoodat :wink: 

So this tweak would then somehow allow to use also a memory card 2 in games which don't support it. One only has to manually disable memory card 1.
