### ISSUE TITLE
Compilation on Gentoo: "capstone.h: No such file or directory"

### ISSUE THREAD

**Issue by RockfordRoe** [grumpycoders/pcsx-redux#869]
When attempting to build the project with `CC="clang" CXX="clang++" CFLAGS="-O3 -m64 -pipe -march=znver3 -static" CXXFLAGS=$CFLAGS LDFLAGS="-fuse-ld=lld" make -j13` on my Gentoo GNU/Linux environment, The compilation process errors out when attempting to build the dynarec outputting: `capstone.h: No such file or directory` although dev-libs/capstone is installed onto the system. 

It's a known bug [that was fixed in QEMU's upstream,](https://patchwork.kernel.org/project/qemu-devel/patch/20180215173539.11033-1-f4bug@amsat.org/) and I believe that a fix like this could be implemented. My ideal solution is migrating to meson or autoconf, but I am still not entirely experienced enough with C++ to try anything hasty nor do I want my opinion to dictate the project.

**Comment by nicolasnoble** [comment]
We're currently using `pkg-config` to detect the environment. What does `pkg-config --cflags capstone` say on  your system?

**Comment by nicolasnoble** [comment]
Oh, I think I see what's going on. Ugh. Okay.

**Comment by nicolasnoble** [comment]
Should be fixed by #871
