### ISSUE TITLE
Linux/Regression: Crash Team Racing SCES-02105 no longer works in later builds

### ISSUE THREAD

**Issue by lorn10** [grumpycoders/pcsx-redux#878]
### Describe the bug

It looks that **Crash Team Racing** SCES-02105 is no longer working in later PCSX-Redux builds like 669b7970 and 9258.

The display output stands at the **Sony Computer Entertainment Europe presents** position while the emulation itself seems to be running somehow. So I can hear the voice in several different languages when I wait.
![Crash_Team_Racing_build_669b7970](https://user-images.githubusercontent.com/9931771/173195294-f8ad23df-3d28-4f7f-ad9b-ef5b1d244d97.png)

### Expected behavior

This should work at least in the way like it works on **PCSX-Reloaded**. :wink:  However, some graphical glitches are also present there so maybe this game is generally a difficult one.

### Steps to reproduce the bug

1. Load the **Crash Team Racing** SCES-02105 game and run it.

### Operating System

Kubuntu 20.04 LTS

### CPU model

Intel Core i5-2500S

### GPU model

AMD Radeon HD 6770M

### BIOS version

both are affected

### CPU emulation mode

Recompiler

### Additional information

This happens with both, PSX OpenBIOS and the regular stock BIOS as well with the recompiler and interpreter. It also happens as mentioned on the Windows build.

**Note**, I have made the ROM image myself with [AcetoneISO](https://en.wikipedia.org/wiki/AcetoneISO).

**Comment by johnbaumann** [comment]
I am unable to reproduce this behavior locally.

Windows + Dynarec + official bios.
Version 9294.20220610.5.x64

**Comment by wheremyfoodat** [comment]
Since this is a EU build, make sure you have the required SBI files in case this is a libcrypt protected game

**Comment by lorn10** [comment]
Thanks for the fast answer! Okay, then this works in **PCSX-Reloaded** because I have loaded the game directly from the CD and not from an image file?

If that's the case then it looks that PCSX-Redux really really needs a **native CD playback** function. :smiley: 

Whatever, I have found regarding those SBI files the page [here](https://psxdatacenter.com/sbifiles.html). There is written under point 2 I quote:

> 2 - Extract them in the **patches folder** of epsxe. 

But there exist no "patches folder" in the PCSX-Redux directory and so far also no "option" to "load" a game related SBI file...

**Comment by nicolasnoble** [comment]
> If that's the case then it looks that PCSX-Redux really really needs a **native CD playback** function. 😃
Not going to happen. 

> Whatever, I have found regarding those SBI files the page [here](https://psxdatacenter.com/sbifiles.html). There is written under point 2 I quote:
> 
> > 2 - Extract them in the **patches folder** of epsxe.
> 
> But there exist no "patches folder" in the PCSX-Redux directory and so far also no "option" to "load" a game related SBI file...
This document doesn't apply. PCSX (not just Redux) works in an easier way. Simply place the sbi file next to the iso, with the same base filename. 

If your Iso is `my game.bin`, place the file `my game.sbi` next to it.

**Comment by lorn10** [comment]
Okay, will test this. But I can run the image file made with [AcetoneISO](https://en.wikipedia.org/wiki/AcetoneISO) perfectly well in **PCSX-Reloaded**. So absolutely no SBI file required there...

**Comment by nicolasnoble** [comment]
http://redump.org/disc/798/ this game indeed has libcrypt fwiw.

**Comment by lorn10** [comment]
And it looks that there are two SCES-02105 versions available, one comes with EDC the other without.

**Comment by lorn10** [comment]
After some further testing I was able to go in-game at least on PCSX-Reloaded but without the use of any SBI file. Maybe there exist some in-built PCSX-Reloaded "CTR tweak"... Whatever, but as said the game doesn't run fully stable, the emulator is crashing randomly at some point.

Regarding PCSX-Redux I was until now unsuccessful, regardless which SBI file (EDC or no-EDC) is used. Eventually this here is in the end also somehow Linux related...

**Comment by lorn10** [comment]
@wheremyfoodat Maybe it would make sense to look into my AcetoneISO generated Crash Team Racing image? I have uploaded it, so if you have some motivation for that you can ping me at kle@bluewin.ch.

This may have in the future some additional relevance because also other people will [make PSX images with AcetoneISO](https://www.youtube.com/watch?v=8zexF07muC8). :wink:

**Comment by wheremyfoodat** [comment]
Can't look into it atm. A quick way to look into it would be running it in Duckstation though. It should show a warning if it doesn't like the image.

**Comment by lorn10** [comment]
A final update to this topic. My self generated **Crash Team Racing** image is working in DuckStation but only with a SBI file. :+1: 

It seems that it doesn't matter which one is used, it works with the EDC variant as well as with the non-EDC one. Without a SBI file DuckStation complains that the image is "incomplete". Maybe such a "libcrypt image" detection mechanism would be a useful addition to PCSX-Redux? :wink: 

Whatever, - I have now again learned quite some stuff. :wink: Many thanks to all for the help and the GREAT work in this project.

Will close this issue. Maybe this will become again relevant with other self-build PSX images by AcetoneISO. Until then, it should be noted that only non-libcrypt protected games are working flawlessly in PCSX-Redux. Will look into this again with Spyro and Spyro 2.

**Comment by wheremyfoodat** [comment]
> Maybe such a "libcrypt image" detection mechanism would be a useful addition to PCSX-Redux?

That would be pretty cool

**Comment by lorn10** [comment]
And it remains a mystery why PCSX-Reloaded can handle this situation at an "almost playable state" without any SBI file....
