### ISSUE TITLE
SPU register access through KSEG1 is broken

### ISSUE THREAD

**Issue by spicyjpeg** [grumpycoders/pcsx-redux#946]
### Describe the bug

Accessing SPU registers using the KSEG1 segment (`0xbf801xxx` instead of `0x1f801xxx`) does not seem to work, even though other peripherals such as the GPU and DMA controller seem to be accessible through KSEG1 without issues. Unsure about whether reading works; writing definitely does not and any values written to the SPU seem to be ignored.

### Expected behavior

See above.

### Steps to reproduce the bug

I've attached two test executables (based on the PSn00bSDK sound example), one accessing the GPU/SPU/DMA controller through the first half of KUSEG and the other using KSEG1 instead. Both work on other emulators and the former also works on pcsx-redux, however the latter fails to transfer data to SPU RAM and does not play any sound. Both initialize the SPU by writing `0x0000` then `0xc001` to the control register, but the value shown in the SPU debugger window never gets updated in the case of the latter.

**The behavior of these executables hasn't been tested on real hardware.**

### Operating System

Windows 10 21H2

### PCSX-Redux version

Version: 9957.20220730.12.x64
Changeset: 5df2b9b41ee7674daa1d4ede4a389afa85297d82
Date & time: 2022-07-30 12:37:18

### CPU model

Ryzen 5 1500X

### GPU model

Radeon RX 590

### BIOS version

Same behavior with openbios and v3.0 US BIOS

### CPU emulation mode

Interpreter

### Additional information

[Test executables here](https://github.com/grumpycoders/pcsx-redux/files/9228734/spu_test_executables.zip)

**Comment by wheremyfoodat** [comment]
Gon look into it in a bit
