### ISSUE TITLE
Controllers connected after launch are no longer detected

### ISSUE THREAD

**Issue by MeharDT** [grumpycoders/pcsx-redux#962]
### Describe the bug

If a gamepad is connected to a machine after the emulator is launched, it is no longer automatically detected and will not work until the emulator is restarted. I can't find any indication that this functionality was intentionally removed, on Windows it's working as of Version 9906.20220727.4. Reverting the changes in the following PR will also restore functionality (specifically, line 53).

https://github.com/grumpycoders/pcsx-redux/pull/941

### Expected behavior

The controller should be detected and usable.

### Steps to reproduce the bug

- Disconnect any gamepads connected to test machine
- Start PCSX-Redux
- Connect a gamepad to the test machine
- Start emulation
- Attempt to use gamepad 

### Operating System

Windows 10

### PCSX-Redux version

Source and 10255.20220809.7.x64

### CPU model

N/A

### GPU model

N/A

### BIOS version

OpenBIOS

### CPU emulation mode

Recompiler

### Additional information

Workaround
Rescanning for gamepads in Configuration -> Controls will allow pcsx-redux to detect the gamepad.

**Comment by nicolasnoble** [comment]
#964 should take care of this.

**Comment by MeharDT** [comment]
> #964 should take care of this.

Nice work! I manually merged your changes into my codebase and can confirm it fixes this issue.

**Comment by nicolasnoble** [comment]
Glad to hear that :)
