### ISSUE TITLE
can i hire you 

### ISSUE THREAD

**Issue by hadoizz** [grumpycoders/pcsx-redux#972]
### Describe the bug

can we do this for website?

### Expected behavior

i need website

### Steps to reproduce the bug

website delvlop

### Operating System

website

### PCSX-Redux version

website

### CPU model

8

### GPU model

8

### BIOS version

8

### CPU emulation mode

Interpreter

### Additional information

8

**Comment by wheremyfoodat** [comment]
The internet is not real, websites are not a thing, sorry.

We might reconsider for the measly price of $400/hr
