### ISSUE TITLE
ImGui assert: tab->ContentWidth > 0.0f is false

### ISSUE THREAD

**Issue by lazycurler** [grumpycoders/pcsx-redux#979]
![image](https://user-images.githubusercontent.com/1229841/184558893-94acd0fe-6d4e-43d6-9ec3-37a41f1ddeea.png)
### Issue: 
The above message is displayed and the program terminates

### To Recreate:
1. Delete the `"imgui"` entry from `pcsx.json` (optional)
2. Open a debug window - for this example I will use "Show Assembly"
3. Place the `Assembly` debug window (blue) such that the upper left corner is slightly out of reach of the monitor (black)
4. Open another debug window - for this example I will use "Show Register"
5. Move the` Register` debug window (red) such that it will cause the existing "Assembly" window to split
6. Program will now display the error message

![image](https://user-images.githubusercontent.com/1229841/184559040-2a18a96b-3e83-4915-9c57-9bef1ba6d3bc.png)
![image](https://user-images.githubusercontent.com/1229841/184559117-ab8cfc88-a41a-4d38-b3e4-49e085760104.png)

### Related Issue:
If a split window is created and then moved into an off screen location as described above, the program will not crash during the current session but will crash upon the next startup essentially softlocking the program until the offending `pcsx.json` line is removed.

### Desired Behavior: 
Program gracefully handles the issue and does not terminate nor cause issues on startup.

**Comment by nicolasnoble** [comment]
I managed to repro it locally with some difficulties. I've tried updating ImGui to latest on the docking branch, but it still happens. I haven't managed to reproduce it with the base ImGui examples yet. But it reeks of an ImGui bug on the docking branch.

I'm sure @ocornut would be interested, but I'll try creating a bug repro on their repository when I manage to properly narrow it down.

**Comment by nicolasnoble** [comment]
Okay, managed to repro-it with the base demo. It's the `ImGuiConfigFlags_DpiEnableScaleFonts` option.

**Comment by nicolasnoble** [comment]
So this one should've been fixed from upstream ImGui, and we've updated to it. Thanks @ocornut!
